"""Mount characteristics.

Mounts are recorded here as data only. Nothing in the combat engine reads this
module yet - a mounted character still fights on foot - so adding a mount
changes no simulation result. Wiring mounts into combat is a separate job:
a mount adds its own Attacks at its own Initiative, contributes its Movement,
and several rules ("Strike First does not apply to this model's mount") turn on
telling rider and mount apart.

A mount's profile borrows the rider's Ballistic Skill, Toughness, Wounds and
Leadership, which the army lists print as a dash. Those are stored as None. A
ridden monster that improves its rider shows the bonus instead ("(+1)" on the
site), stored as the string "+1".

Mounts with more than one row (chariots with their crew and beasts, monsters
with a howdah crew) keep every row under `profiles`; the top-level statline is
the row named after the mount, or the first row.

Keys are the site's own names, with "(Mount)" dropped. Several armies share a
mount name for different profiles, so those keep the site's qualifier:
"Warhorse (Bretonnia)" and "Warhorse (Realms of Men)" differ in their rules.
`points` is the cost for a character to take the mount.

Generated from https://tow.whfb.app/unit/<url> by tools/transcribe_mounts.py,
except the three entries at the end, which exist only as a row on their
rider's page.
"""

from __future__ import annotations

# name -> profile.
Mounts = {
    'Abyssal Terror': {
        'url': 'abyssal-terror',
        'points': 120,
        'troop_type': 'MonstrousCreature',
        'Movement': 6,
        'WeaponSkill': 4,
        'BallisticSkill': None,
        'Strength': 5,
        'Toughness': '+1',
        'Initiative': 2,
        'Wounds': '+4',
        'Attacks': 3,
        'Leadership': None,
        'SpecialRules': ['Close Order', 'Fly (9)', 'Large Target', 'Necromantic Undead', 'Stomp Attacks (D3)', 'Swiftstride', 'Terror'],
        'equipment': 'Wicked claws, poisonous tail and scaly skin (counts as heavy armour)',
    },
    'Ancient Stegadon': {
        'url': 'ancient-stegadon',
        'points': 230,
        'troop_type': 'Behemoth',
        'armour_value': '4+',
        'Movement': 6,
        'WeaponSkill': 4,
        'BallisticSkill': None,
        'Strength': 6,
        'Toughness': 6,
        'Initiative': 1,
        'Wounds': 5,
        'Attacks': 3,
        'Leadership': None,
        'SpecialRules': ['Close Order', 'Cold Blooded', 'Howdah', 'Immune to Psychology', 'Impact Hits (D3+1)', 'Large Target', 'Poisoned Attacks (javelins only)', 'Stomp Attacks (D3+2)', 'Stubborn', 'Terror'],
        'equipment': '- Ancient Stegadon: Great horns and giant bow\n- Skink Crew: Hand weapons and javelins',
        "profiles": [
            {'Name': 'Ancient Stegadon', 'Movement': 6, 'WeaponSkill': 4, 'BallisticSkill': None, 'Strength': 6, 'Toughness': 6, 'Initiative': 1, 'Wounds': 5, 'Attacks': 3, 'Leadership': None},
            {'Name': 'Skink Crew (x5)', 'Movement': None, 'WeaponSkill': 2, 'BallisticSkill': 3, 'Strength': 3, 'Toughness': None, 'Initiative': 4, 'Wounds': None, 'Attacks': 1, 'Leadership': 6},
        ],
    },
    'Arachnarok Spider': {
        'url': 'arachnarok-spider',
        'points': 310,
        'troop_type': 'Behemoth',
        'armour_value': '4+',
        'Movement': 7,
        'WeaponSkill': 4,
        'BallisticSkill': None,
        'Strength': 5,
        'Toughness': 6,
        'Initiative': 4,
        'Wounds': 7,
        'Attacks': 6,
        'Leadership': None,
        'SpecialRules': ['Close Order', 'Howdah', 'Immune to Psychology', 'Large Target', 'Move Through Cover', 'Poisoned Attacks', 'Stomp Attacks (D6)', 'Stubborn', 'Swiftstride', 'Terror'],
        'equipment': '- Arachnarok Spider: Poisonous fangs (counts as a hand weapon) and venom surge\n- Goblin Crew: Hand weapons, cavalry spears and shortbows',
        "profiles": [
            {'Name': 'Arachnarok Spider', 'Movement': 7, 'WeaponSkill': 4, 'BallisticSkill': None, 'Strength': 5, 'Toughness': 6, 'Initiative': 4, 'Wounds': 7, 'Attacks': 6, 'Leadership': None},
            {'Name': 'Goblin Crew (x8)', 'Movement': None, 'WeaponSkill': 2, 'BallisticSkill': 3, 'Strength': 3, 'Toughness': None, 'Initiative': 3, 'Wounds': None, 'Attacks': 1, 'Leadership': 7},
        ],
    },
    'Bale Taurus': {
        'url': 'bale-taurus',
        'points': 160,
        'troop_type': 'Behemoth',
        'Movement': 6,
        'WeaponSkill': 5,
        'BallisticSkill': None,
        'Strength': 6,
        'Toughness': '+1',
        'Initiative': 3,
        'Wounds': '+4',
        'Attacks': 4,
        'Leadership': None,
        'SpecialRules': ['Blazing Body', 'Born of Fire', 'Ward3 (Flaming)', 'Close Order', 'Fly (9)', 'Furious Charge', 'Large Target', 'Stomp Attacks (D3+1)', 'Swiftstride', 'Terror'],
        'equipment': 'Trampling hooves and goring horns',
    },
    'Barded Elven Steed': {
        'url': 'barded-elven-steed',
        'points': 18,
        'troop_type': 'HeavyCavalry',
        'Movement': 8,
        'WeaponSkill': 3,
        'BallisticSkill': None,
        'Strength': 3,
        'Toughness': None,
        'Initiative': 4,
        'Wounds': None,
        'Attacks': 1,
        'Leadership': None,
        'SpecialRules': ['Counter Charge', 'First Charge', 'Ithilmar Barding', 'Swiftstride'],
        'equipment': 'Hooves (counts as a hand weapon) and barding',
    },
    'Barded Pegasus': {
        'url': 'barded-pegasus',
        'points': 30,
        'troop_type': 'MonstrousCavalry',
        'Movement': 7,
        'WeaponSkill': 3,
        'BallisticSkill': None,
        'Strength': 4,
        'Toughness': None,
        'Initiative': 4,
        'Wounds': '+1',
        'Attacks': 2,
        'Leadership': None,
        'SpecialRules': ['Counter Charge', 'First Charge', 'Fly (10)', 'Swiftstride'],
        'equipment': 'Iron-shod hooves (counts as a hand weapon) and barding',
    },
    'Barded Skeletal Steed': {
        'url': 'barded-skeletal-steed',
        'points': 16,
        'troop_type': 'HeavyCavalry',
        'Movement': 7,
        'WeaponSkill': 2,
        'BallisticSkill': None,
        'Strength': 3,
        'Toughness': None,
        'Initiative': 2,
        'Wounds': None,
        'Attacks': 1,
        'Leadership': None,
        'SpecialRules': ['Counter Charge', 'Nehekharan Undead', 'Swiftstride', 'Vanguard'],
        'equipment': 'Skeletal hooves (counts as hand weapon) and barding',
    },
    'Barded Warhorse': {
        'url': 'barded-warhorse',
        'points': 16,
        'troop_type': 'HeavyCavalry',
        'Movement': 7,
        'WeaponSkill': 3,
        'BallisticSkill': None,
        'Strength': 3,
        'Toughness': None,
        'Initiative': 3,
        'Wounds': None,
        'Attacks': 1,
        'Leadership': None,
        'SpecialRules': ['Counter Charge', 'First Charge', 'Swiftstride'],
        'equipment': 'Iron-shod hooves (counts as a hand weapon) and barding',
    },
    'Black Dragon': {
        'url': 'black-dragon',
        'points': 280,
        'troop_type': 'Behemoth',
        'Movement': 6,
        'WeaponSkill': 6,
        'BallisticSkill': None,
        'Strength': 7,
        'Toughness': '+3',
        'Initiative': 4,
        'Wounds': '+6',
        'Attacks': 6,
        'Leadership': None,
        'SpecialRules': ['Close Order', 'Fly (10)', 'Hatred (High Elves)', 'Large Target', 'Stomp Attacks (D6)', 'Swiftstride', 'Terror'],
        'equipment': 'Wicked claws, serrated maw, noxious breath and draconic scales (counts as full plate armour)',
    },
    'Black Orc Boar Chariot': {
        'url': 'black-orc-boar-chariot',
        'points': 130,
        'troop_type': 'HeavyChariot',
        'armour_value': '3+',
        'Movement': None,
        'WeaponSkill': None,
        'BallisticSkill': None,
        'Strength': 5,
        'Toughness': 5,
        'Initiative': None,
        'Wounds': 4,
        'Attacks': None,
        'Leadership': None,
        'SpecialRules': ['Choppas', 'Close Order', 'First Charge', 'Furious Charge (Black Orc Crew only)', 'Ignore Panic', 'Impact Hits (D6+1)', 'Tusker Charge'],
        'equipment': '- Black Orc Crew: Hand weapons\n- War Boars: Tusks (counts as hand weapons)',
        "profiles": [
            {'Name': 'Chariot', 'Movement': None, 'WeaponSkill': None, 'BallisticSkill': None, 'Strength': 5, 'Toughness': 5, 'Initiative': None, 'Wounds': 4, 'Attacks': None, 'Leadership': None},
            {'Name': 'Black Orc Crew (x2)', 'Movement': None, 'WeaponSkill': 4, 'BallisticSkill': 3, 'Strength': 4, 'Toughness': 4, 'Initiative': 3, 'Wounds': None, 'Attacks': 1, 'Leadership': 8},
            {'Name': 'War Boars (x2)', 'Movement': 7, 'WeaponSkill': 3, 'BallisticSkill': None, 'Strength': 3, 'Toughness': None, 'Initiative': 3, 'Wounds': None, 'Attacks': 1, 'Leadership': None},
        ],
    },
    'Blood Throne of Khorne': {
        'url': 'blood-throne-of-khorne',
        'points': 160,
        'troop_type': 'HeavyChariot',
        'armour_value': '4+',
        'Movement': 7,
        'WeaponSkill': 5,
        'BallisticSkill': None,
        'Strength': 5,
        'Toughness': 5,
        'Initiative': 2,
        'Wounds': 4,
        'Attacks': 3,
        'Leadership': None,
        'SpecialRules': ['Close Order', 'Daemonic', 'Daemons of Khorne', 'First Charge', 'Gorefeast', 'Impact Hits (D6+1)', 'Impetuous', 'Totem of Endless Bloodletting'],
        'equipment': '- Blood Throne: Brazen wheels and scything blades (counts as a hand weapon)\n- Bloodletter Crew: Hellblades',
        "profiles": [
            {'Name': 'Blood Throne', 'Movement': 7, 'WeaponSkill': 5, 'BallisticSkill': None, 'Strength': 5, 'Toughness': 5, 'Initiative': 2, 'Wounds': 4, 'Attacks': 3, 'Leadership': None},
            {'Name': 'Bloodletter Crew (x2)', 'Movement': None, 'WeaponSkill': 5, 'BallisticSkill': 3, 'Strength': 4, 'Toughness': None, 'Initiative': 4, 'Wounds': None, 'Attacks': 1, 'Leadership': 7},
        ],
    },
    'Bretonnian Warhorse': {
        'url': 'bretonnian-warhorse',
        'points': 16,
        'troop_type': 'HeavyCavalry',
        'Movement': 8,
        'WeaponSkill': 3,
        'BallisticSkill': None,
        'Strength': 3,
        'Toughness': None,
        'Initiative': 3,
        'Wounds': None,
        'Attacks': 1,
        'Leadership': None,
        'SpecialRules': ['Counter Charge', 'Finest Warhorses', 'First Charge', 'Swiftstride'],
        'equipment': 'Iron-shod hooves (counts as a hand weapon) and barding',
    },
    'Burning Chariot of Tzeentch': {
        'url': 'burning-chariot-of-tzeentch',
        'points': 190,
        'troop_type': 'HeavyChariot',
        'armour_value': '4+',
        'Movement': None,
        'WeaponSkill': None,
        'BallisticSkill': None,
        'Strength': 4,
        'Toughness': 4,
        'Initiative': None,
        'Wounds': 4,
        'Attacks': None,
        'Leadership': None,
        'SpecialRules': ['Close Order', 'Daemonic', 'Daemons of Tzeentch', 'Fly (9)', 'Impact Hits (D6+1)', 'Lore of Daemons', 'Slashing Attack (Screamers only)'],
        'equipment': "- Exalted Flamer: Hand weapon and warpflame\n- Blue Horror Crew: Hand weapons and flames of Tzeentch\n- Screamer: Lamprey's bite",
        "profiles": [
            {'Name': 'Burning Chariot of Tzeentch', 'Movement': None, 'WeaponSkill': None, 'BallisticSkill': None, 'Strength': 4, 'Toughness': 4, 'Initiative': None, 'Wounds': 4, 'Attacks': None, 'Leadership': None},
            {'Name': 'Exalted Flamer', 'Movement': None, 'WeaponSkill': 2, 'BallisticSkill': 5, 'Strength': 4, 'Toughness': None, 'Initiative': 4, 'Wounds': None, 'Attacks': 2, 'Leadership': 7},
            {'Name': 'Blue Horror Crew (x3)', 'Movement': None, 'WeaponSkill': 2, 'BallisticSkill': 3, 'Strength': 3, 'Toughness': None, 'Initiative': 3, 'Wounds': None, 'Attacks': 1, 'Leadership': 7},
            {'Name': 'Screamer (x2)', 'Movement': 1, 'WeaponSkill': 3, 'BallisticSkill': None, 'Strength': 4, 'Toughness': None, 'Initiative': 4, 'Wounds': None, 'Attacks': 2, 'Leadership': None},
        ],
    },
    'Carnosaur': {
        'url': 'carnosaur',
        'points': 170,
        'troop_type': 'Behemoth',
        'Movement': 7,
        'WeaponSkill': 3,
        'BallisticSkill': 0,
        'Strength': 7,
        'Toughness': '+1',
        'Initiative': 2,
        'Wounds': '+4',
        'Attacks': 4,
        'Leadership': None,
        'SpecialRules': ['Blood Frenzy', 'Close Order', 'Cold Blooded', 'Large Target', 'Stomp Attacks (2)', 'Swiftstride', 'Terror'],
        'equipment': 'Slashing talons and scaly skin (counts as heavy armour)',
    },
    'Cathayan Horse': {
        'url': 'cathayan-horse',
        'points': 16,
        'troop_type': 'HeavyCavalry',
        'Movement': 7,
        'WeaponSkill': 3,
        'BallisticSkill': None,
        'Strength': 3,
        'Toughness': None,
        'Initiative': 3,
        'Wounds': None,
        'Attacks': 1,
        'Leadership': None,
        'SpecialRules': ['Counter Charge', 'Swiftstride'],
        'equipment': 'Iron-shod hooves (counts as a hand weapon) and barding',
    },
    'Cathayan Warhorse': {
        'url': 'cathayan-warhorse',
        'points': 16,
        'troop_type': 'HeavyCavalry',
        'Movement': 7,
        'WeaponSkill': 3,
        'BallisticSkill': None,
        'Strength': 3,
        'Toughness': None,
        'Initiative': 3,
        'Wounds': None,
        'Attacks': 1,
        'Leadership': None,
        'SpecialRules': ['Cathayan Cataphracts', 'Counter Charge', 'Swiftstride'],
        'equipment': 'Iron-shod hooves (counts as a hand weapon) and barding',
    },
    'Cauldron of Blood': {
        'url': 'cauldron-of-blood',
        'points': 150,
        'troop_type': 'HeavyChariot',
        'armour_value': '4+',
        'Movement': 2,
        'WeaponSkill': None,
        'BallisticSkill': None,
        'Strength': 5,
        'Toughness': 5,
        'Initiative': None,
        'Wounds': 5,
        'Attacks': None,
        'Leadership': None,
        'SpecialRules': ['Blessings of Khaine', 'Close Order', 'Dragged Along', 'Elven Reflexes', 'Frenzy', 'Hatred (High Elves)', 'Impact Hits (D6+1)', 'Large Target', 'Magic Resistance (-1)', 'Murderous', 'Poisoned Attacks', 'Terror'],
        'equipment': '- Witch Elf Crew: Two hand weapons',
        "profiles": [
            {'Name': 'Cauldron of Blood', 'Movement': 2, 'WeaponSkill': None, 'BallisticSkill': None, 'Strength': 5, 'Toughness': 5, 'Initiative': None, 'Wounds': 5, 'Attacks': None, 'Leadership': None},
            {'Name': 'Witch Elf Crew (x2)', 'Movement': None, 'WeaponSkill': 4, 'BallisticSkill': 4, 'Strength': 3, 'Toughness': None, 'Initiative': 5, 'Wounds': None, 'Attacks': 1, 'Leadership': 9},
        ],
    },
    'Chaos Chariot': {
        'url': 'chaos-chariot',
        'points': 110,
        'troop_type': 'HeavyChariot',
        'armour_value': '3+',
        'Movement': None,
        'WeaponSkill': None,
        'BallisticSkill': None,
        'Strength': 5,
        'Toughness': 5,
        'Initiative': None,
        'Wounds': 4,
        'Attacks': None,
        'Leadership': None,
        'SpecialRules': ['Close Order', 'Ensorcelled Weapons', 'First Charge', 'Impact Hits (D6+1)', 'Mark of Chaos Undivided'],
        'equipment': '- Chaos Charioteers: Hand weapons and halberds\n- Chaos Steeds: Iron-shod hooves (counts as a hand weapon)',
        "profiles": [
            {'Name': 'Chariot', 'Movement': None, 'WeaponSkill': None, 'BallisticSkill': None, 'Strength': 5, 'Toughness': 5, 'Initiative': None, 'Wounds': 4, 'Attacks': None, 'Leadership': None},
            {'Name': 'Chaos Charioteer (x2)', 'Movement': None, 'WeaponSkill': 5, 'BallisticSkill': 3, 'Strength': 4, 'Toughness': None, 'Initiative': 4, 'Wounds': None, 'Attacks': 1, 'Leadership': 8},
            {'Name': 'Chaos Steed (x2)', 'Movement': 7, 'WeaponSkill': 3, 'BallisticSkill': None, 'Strength': 4, 'Toughness': None, 'Initiative': 3, 'Wounds': None, 'Attacks': 1, 'Leadership': None},
        ],
    },
    'Chaos Dragon': {
        'url': 'chaos-dragon',
        'points': 285,
        'troop_type': 'Behemoth',
        'Movement': 6,
        'WeaponSkill': 6,
        'BallisticSkill': None,
        'Strength': 7,
        'Toughness': '+1',
        'Initiative': 4,
        'Wounds': '+6',
        'Attacks': 6,
        'Leadership': None,
        'SpecialRules': ['Close Order', 'Fly (10)', 'Impetuous', 'Large Target', 'Stomp Attacks (D6)', 'Swiftstride', 'Terror', 'Two-headed Dragon'],
        'equipment': 'Wicked claws, Dark Fire of Chaos, Fumes of Contagion and draconic scales (counts as full plate armour)',
    },
    'Chaos Steed': {
        'url': 'chaos-steed',
        'points': 16,
        'troop_type': 'HeavyCavalry',
        'Movement': 7,
        'WeaponSkill': 3,
        'BallisticSkill': None,
        'Strength': 4,
        'Toughness': None,
        'Initiative': 3,
        'Wounds': None,
        'Attacks': 1,
        'Leadership': None,
        'SpecialRules': ['Counter Charge', 'First Charge', 'Swiftstride'],
        'equipment': 'Iron-shod hooves (counts as a hand weapon) and barding',
    },
    'Chariot of Tzeentch': {
        'url': 'chariot-of-tzeentch',
        'points': 90,
        'troop_type': 'HeavyChariot',
        'armour_value': '4+',
        'Movement': None,
        'WeaponSkill': None,
        'BallisticSkill': None,
        'Strength': 4,
        'Toughness': 4,
        'Initiative': None,
        'Wounds': 4,
        'Attacks': None,
        'Leadership': None,
        'SpecialRules': ['Close Order', 'Daemonic', 'Daemons of Tzeentch', 'Fly (9)', 'Impact Hits (D6+1)', 'Slashing Attack (Screamers only)'],
        'equipment': "- Screamer: Lamprey's bite",
        "profiles": [
            {'Name': 'Chariot of Tzeentch', 'Movement': None, 'WeaponSkill': None, 'BallisticSkill': None, 'Strength': 4, 'Toughness': 4, 'Initiative': None, 'Wounds': 4, 'Attacks': None, 'Leadership': None},
            {'Name': 'Screamer (x2)', 'Movement': 1, 'WeaponSkill': 3, 'BallisticSkill': None, 'Strength': 4, 'Toughness': None, 'Initiative': 4, 'Wounds': None, 'Attacks': 2, 'Leadership': None},
        ],
    },
    "Chieftain's Chariot": {
        'url': 'chieftains-chariot',
        'points': 105,
        'troop_type': 'HeavyChariot',
        'armour_value': '4+',
        'Movement': None,
        'WeaponSkill': None,
        'BallisticSkill': None,
        'Strength': 5,
        'Toughness': 4,
        'Initiative': None,
        'Wounds': 3,
        'Attacks': None,
        'Leadership': None,
        'SpecialRules': ['Armour Bane (1, Chracian Lions only)', 'Close Order', 'Elven Reflexes', 'Fear', 'First Charge', "Impact Hits (D6, Chieftain's Chariot only)", 'Stubborn', 'Valour of Ages'],
        'equipment': '- Charioteers: Hand weapons and Chracian great blade\n- Characian Lions: Claws and fangs (counts as a hand weapon)',
        "profiles": [
            {'Name': "Chieftain's Chariot", 'Movement': None, 'WeaponSkill': None, 'BallisticSkill': None, 'Strength': 5, 'Toughness': 4, 'Initiative': None, 'Wounds': 3, 'Attacks': None, 'Leadership': None},
            {'Name': 'Charioteer (x1)', 'Movement': None, 'WeaponSkill': 5, 'BallisticSkill': 4, 'Strength': 4, 'Toughness': None, 'Initiative': 4, 'Wounds': None, 'Attacks': 1, 'Leadership': None},
            {'Name': 'Chracian Lion (x2)', 'Movement': 8, 'WeaponSkill': 5, 'BallisticSkill': None, 'Strength': 4, 'Toughness': None, 'Initiative': 4, 'Wounds': None, 'Attacks': 2, 'Leadership': None},
        ],
    },
    'Cold One (Dark Elves)': {
        'url': 'cold-one-dark-elves',
        'points': 18,
        'troop_type': 'HeavyCavalry',
        'Movement': 7,
        'WeaponSkill': 3,
        'BallisticSkill': None,
        'Strength': 4,
        'Toughness': '+1',
        'Initiative': 2,
        'Wounds': None,
        'Attacks': 2,
        'Leadership': None,
        'SpecialRules': ['Armour Bane (1, Cold One only)', 'Armoured Hide (1)', 'Fear', 'First Charge', 'Stupidity', 'Swiftstride'],
        'equipment': 'Claws and teeth (counts as a hand weapon)',
    },
    'Cold One (Lizardmen)': {
        'url': 'cold-one-lizardmen',
        'points': 18,
        'troop_type': 'HeavyCavalry',
        'Movement': 7,
        'WeaponSkill': 3,
        'BallisticSkill': None,
        'Strength': 4,
        'Toughness': None,
        'Initiative': 2,
        'Wounds': None,
        'Attacks': 2,
        'Leadership': None,
        'SpecialRules': ['Armour Bane (1, Cold One only)', 'Armoured Hide (1)', 'Fear', 'Stupidity', 'Swiftstride'],
        'equipment': 'Claws and teeth (counts as a hand weapon)',
    },
    'Cold One Chariot': {
        'url': 'cold-one-chariot',
        'points': 125,
        'troop_type': 'HeavyChariot',
        'armour_value': '4+',
        'Movement': None,
        'WeaponSkill': None,
        'BallisticSkill': None,
        'Strength': 5,
        'Toughness': 5,
        'Initiative': None,
        'Wounds': 4,
        'Attacks': None,
        'Leadership': None,
        'SpecialRules': ['Armour Bane (1, Cold One only)', 'Close Order', 'Elven Reflexes', 'Fear', 'First Charge', 'Hatred (High Elves)', 'Impact Hits (D6+1)', 'Stupidity'],
        'equipment': '- Knight Charioteers: Hand weapons, cavalry spears and repeater crossbows\n- Cold Ones: Claws and teeth (counts as a hand weapons)',
        "profiles": [
            {'Name': 'Chariot', 'Movement': None, 'WeaponSkill': None, 'BallisticSkill': None, 'Strength': 5, 'Toughness': 5, 'Initiative': None, 'Wounds': 4, 'Attacks': None, 'Leadership': None},
            {'Name': 'Knight Charioteer (x2)', 'Movement': None, 'WeaponSkill': 5, 'BallisticSkill': 4, 'Strength': 4, 'Toughness': None, 'Initiative': 5, 'Wounds': None, 'Attacks': 1, 'Leadership': 9},
            {'Name': 'Cold One (x2)', 'Movement': 7, 'WeaponSkill': 3, 'BallisticSkill': None, 'Strength': 4, 'Toughness': None, 'Initiative': 2, 'Wounds': None, 'Attacks': 2, 'Leadership': None},
        ],
    },
    'Coven Throne': {
        'url': 'coven-throne',
        'points': 210,
        'troop_type': 'HeavyChariot',
        'armour_value': '4+',
        'Movement': None,
        'WeaponSkill': None,
        'BallisticSkill': None,
        'Strength': 5,
        'Toughness': 5,
        'Initiative': None,
        'Wounds': 5,
        'Attacks': None,
        'Leadership': None,
        'SpecialRules': ['Close Order', 'Dark Vitality', 'First Charge', 'Fly (8)', 'Ghoulish Glamour', 'Enemy Must Pass Leadership To Hit', 'Impact Hits (D6+1)', 'Large Target', 'Necromantic Undead', 'Random Attacks (Spirit Horde only)', 'Regeneration (6+)', 'Scrying Pool'],
        'equipment': '- Pallid Handmaidens: Hand weapons\n- Spirit Horde: Hand weapons and lances',
        "profiles": [
            {'Name': 'Coven Throne', 'Movement': None, 'WeaponSkill': None, 'BallisticSkill': None, 'Strength': 5, 'Toughness': 5, 'Initiative': None, 'Wounds': 5, 'Attacks': None, 'Leadership': None},
            {'Name': 'Pallid Handmaidens (x2)', 'Movement': None, 'WeaponSkill': 5, 'BallisticSkill': 3, 'Strength': 5, 'Toughness': None, 'Initiative': 5, 'Wounds': None, 'Attacks': 2, 'Leadership': 7},
            {'Name': 'Spirit Horde', 'Movement': 6, 'WeaponSkill': 3, 'BallisticSkill': 0, 'Strength': 3, 'Toughness': None, 'Initiative': 1, 'Wounds': None, 'Attacks': 'D6', 'Leadership': None},
        ],
    },
    'Daemonic Mount': {
        'url': 'daemonic-mount',
        'points': 35,
        'troop_type': 'MonstrousCavalry',
        'Movement': 8,
        'WeaponSkill': 4,
        'BallisticSkill': None,
        'Strength': 5,
        'Toughness': None,
        'Initiative': 3,
        'Wounds': '+1',
        'Attacks': 2,
        'Leadership': None,
        'SpecialRules': ['Armour Bane (1, Daemonic Mount only)', 'Counter Charge', 'Fear', 'Magical Attacks', 'Mark of Chaos (as rider)', 'Stomp Attacks (1)', 'Swiftstride'],
        'equipment': 'Daemonic hooves (counts as a hand weapon) and barding',
    },
    'Dark Pegasus': {
        'url': 'dark-pegasus',
        'points': 35,
        'troop_type': 'MonstrousCavalry',
        'Movement': 8,
        'WeaponSkill': 3,
        'BallisticSkill': None,
        'Strength': 4,
        'Toughness': None,
        'Initiative': 4,
        'Wounds': '+1',
        'Attacks': 3,
        'Leadership': None,
        'SpecialRules': ['Armour Bane (1, Dark Pegasus only)', 'Counter Charge', 'First Charge', 'Fly (10)', 'Swiftstride'],
        'equipment': 'Hooves (counts as a hand weapon)',
    },
    'Dark Steed': {
        'url': 'dark-steed',
        'points': 14,
        'troop_type': 'LightCavalry',
        'Movement': 9,
        'WeaponSkill': 3,
        'BallisticSkill': None,
        'Strength': 3,
        'Toughness': None,
        'Initiative': 4,
        'Wounds': None,
        'Attacks': 1,
        'Leadership': None,
        'SpecialRules': ['Fast Cavalry', 'Swiftstride'],
        'equipment': 'Hooves (counts as a hand weapon)',
    },
    'Demigryph': {
        'url': 'demigryph',
        'points': 50,
        'troop_type': 'MonstrousCavalry',
        'Movement': 7,
        'WeaponSkill': 4,
        'BallisticSkill': None,
        'Strength': 5,
        'Toughness': None,
        'Initiative': 4,
        'Wounds': '+1',
        'Attacks': 3,
        'Leadership': None,
        'SpecialRules': ['Counter Charge', 'First Charge', 'Fear', 'Swiftstride'],
        'equipment': 'Wicked claws and barding',
    },
    'Disc of Tzeentch': {
        'url': 'disc-of-tzeentch',
        'points': 20,
        'troop_type': 'LightCavalry',
        'Movement': 1,
        'WeaponSkill': 3,
        'BallisticSkill': None,
        'Strength': 4,
        'Toughness': None,
        'Initiative': 4,
        'Wounds': None,
        'Attacks': 3,
        'Leadership': None,
        'SpecialRules': ['Daemonic', 'Daemon of Tzeentch', 'Fly (10)', 'Swiftstride'],
        'equipment': 'Tentacles (counts as a hand weapon)',
    },
    'Elven Steed': {
        'url': 'elven-steed',
        'points': 14,
        'troop_type': 'LightCavalry',
        'Movement': 9,
        'WeaponSkill': 3,
        'BallisticSkill': None,
        'Strength': 3,
        'Toughness': None,
        'Initiative': 4,
        'Wounds': None,
        'Attacks': 1,
        'Leadership': None,
        'SpecialRules': ['Fast Cavalry', 'Swiftstride'],
        'equipment': 'Hooves (counts as a hand weapon)',
    },
    'Empire War Wagon': {
        'url': 'empire-war-wagon',
        'points': 140,
        'troop_type': 'HeavyChariot',
        'armour_value': '3+',
        'Movement': None,
        'WeaponSkill': None,
        'BallisticSkill': None,
        'Strength': 5,
        'Toughness': 5,
        'Initiative': None,
        'Wounds': 6,
        'Attacks': None,
        'Leadership': None,
        'SpecialRules': ['Close Order', 'Crushing Weight', 'Impact Hits (D6+1, War Wagon only)', 'Large Target', 'Stable Firing Platform', 'Stomp Attacks (D3+1)'],
        'equipment': '- War Wagon Crew: Hand weapons and assorted weapons\n- Barded Warhorses: Iron-shod hooves (counts as a hand weapon)',
        "profiles": [
            {'Name': 'War Wagon', 'Movement': None, 'WeaponSkill': None, 'BallisticSkill': None, 'Strength': 5, 'Toughness': 5, 'Initiative': None, 'Wounds': 6, 'Attacks': None, 'Leadership': None},
            {'Name': 'War Wagon Crew (x6)', 'Movement': None, 'WeaponSkill': 3, 'BallisticSkill': 3, 'Strength': 3, 'Toughness': None, 'Initiative': 3, 'Wounds': None, 'Attacks': 1, 'Leadership': 8},
            {'Name': 'Barded Warhorse (x2)', 'Movement': 7, 'WeaponSkill': 3, 'BallisticSkill': None, 'Strength': 3, 'Toughness': None, 'Initiative': 3, 'Wounds': None, 'Attacks': 1, 'Leadership': None},
        ],
    },
    'Empire Warhorse': {
        'url': 'empire-warhorse',
        'points': 12,
        'troop_type': 'LightCavalry',
        'Movement': 8,
        'WeaponSkill': 3,
        'BallisticSkill': None,
        'Strength': 3,
        'Toughness': None,
        'Initiative': 3,
        'Wounds': None,
        'Attacks': 1,
        'Leadership': None,
        'SpecialRules': ['Fast Cavalry', 'Swiftstride'],
        'equipment': 'Iron-shod hooves (counts as a hand weapon)',
    },
    'Exalted Seeker Chariot of Slaanesh': {
        'url': 'exalted-seeker-chariot-of-slaanesh',
        'points': 185,
        'troop_type': 'HeavyChariot',
        'armour_value': '4+',
        'Movement': None,
        'WeaponSkill': None,
        'BallisticSkill': None,
        'Strength': 4,
        'Toughness': 4,
        'Initiative': None,
        'Wounds': 6,
        'Attacks': None,
        'Leadership': None,
        'SpecialRules': ['Armour Bane (1, Steed of Slaanesh only)', 'Close Order', 'Daemonic', 'Daemons of Slaanesh', 'First Charge', 'Impact Hits (D6+1)', 'Poisoned Attacks (Steed of Slaanesh only)'],
        'equipment': '- Daemonette Crew: Piercing claws\n- Steeds of Slaanesh: Claws and fangs (counts as hand weapons)',
        "profiles": [
            {'Name': 'Exalted Seeker Chariot', 'Movement': None, 'WeaponSkill': None, 'BallisticSkill': None, 'Strength': 4, 'Toughness': 4, 'Initiative': None, 'Wounds': 6, 'Attacks': None, 'Leadership': None},
            {'Name': 'Daemonette Crew (x3)', 'Movement': None, 'WeaponSkill': 4, 'BallisticSkill': 3, 'Strength': 3, 'Toughness': None, 'Initiative': 5, 'Wounds': None, 'Attacks': 1, 'Leadership': 7},
            {'Name': 'Steed of Slaanesh (x4)', 'Movement': 9, 'WeaponSkill': 3, 'BallisticSkill': None, 'Strength': 3, 'Toughness': None, 'Initiative': 5, 'Wounds': None, 'Attacks': 1, 'Leadership': None},
        ],
    },
    'Forest Dragon': {
        'url': 'forest-dragon',
        'points': 275,
        'troop_type': 'Behemoth',
        'Movement': 6,
        'WeaponSkill': 6,
        'BallisticSkill': None,
        'Strength': 7,
        'Toughness': '+3',
        'Initiative': 4,
        'Wounds': '+6',
        'Attacks': 6,
        'Leadership': None,
        'SpecialRules': ['Close Order', 'Fly (10)', 'Large Target', 'Stomp Attacks (D6)', 'Swiftstride', 'Terror'],
        'equipment': 'Wicked claws, serrated maw, soporific breath and draconic scales (counts as full plate armour)',
    },
    'Giant Cave Squig': {
        'url': 'giant-cave-squig',
        'points': 25,
        'troop_type': 'MonstrousCavalry',
        'Movement': '3D6',
        'WeaponSkill': 4,
        'BallisticSkill': None,
        'Strength': 5,
        'Toughness': None,
        'Initiative': 3,
        'Wounds': '+1',
        'Attacks': 3,
        'Leadership': None,
        'SpecialRules': ['Armoured Hide (1)', 'Hatred (Dwarfs)', 'Impact Hits (D3)', 'Loner', 'Random Movement'],
        'equipment': 'Massive Gob',
    },
    'Giant Wolf': {
        'url': 'giant-wolf',
        'points': 10,
        'troop_type': 'LightCavalry',
        'Movement': 9,
        'WeaponSkill': 3,
        'BallisticSkill': None,
        'Strength': 3,
        'Toughness': None,
        'Initiative': 3,
        'Wounds': None,
        'Attacks': 1,
        'Leadership': None,
        'SpecialRules': ['Chariot Runners', 'Fast Cavalry', 'Fire & Flee', 'Swiftstride'],
        'equipment': 'Claws and fangs (counts as a hand weapon)',
    },
    'Gigantic Spider': {
        'url': 'gigantic-spider',
        'points': 35,
        'troop_type': 'LightCavalry',
        'Movement': 7,
        'WeaponSkill': 4,
        'BallisticSkill': None,
        'Strength': 4,
        'Toughness': None,
        'Initiative': 4,
        'Wounds': '+1',
        'Attacks': 3,
        'Leadership': None,
        'SpecialRules': ['Armoured Hide (1)', 'Fast Cavalry', 'Move Through Cover', 'Poisoned Attacks', 'Swiftstride'],
        'equipment': 'Claws and fangs (counts as a hand weapon)',
    },
    'Goblin Wolf Chariot': {
        'url': 'goblin-wolf-chariot',
        'points': 53,
        'troop_type': 'LightChariot',
        'armour_value': '5+',
        'Movement': None,
        'WeaponSkill': None,
        'BallisticSkill': None,
        'Strength': 5,
        'Toughness': 4,
        'Initiative': None,
        'Wounds': 3,
        'Attacks': None,
        'Leadership': None,
        'SpecialRules': ['Fear of Elves', 'Impact Hits (D3+1)', 'Impetuous', 'Open Order', 'Swiftstride', 'Warband'],
        'equipment': '- Goblin Crew: Hand weapons, cavalry spears and shortbows\n- Giant Wolves: Claws and fangs (counts as hand weapons)',
        "profiles": [
            {'Name': 'Chariot', 'Movement': None, 'WeaponSkill': None, 'BallisticSkill': None, 'Strength': 5, 'Toughness': 4, 'Initiative': None, 'Wounds': 3, 'Attacks': None, 'Leadership': None},
            {'Name': 'Goblin Crew (x3)', 'Movement': None, 'WeaponSkill': 2, 'BallisticSkill': 3, 'Strength': 3, 'Toughness': None, 'Initiative': 3, 'Wounds': None, 'Attacks': 1, 'Leadership': 6},
            {'Name': 'Giant Wolves (x2)', 'Movement': 9, 'WeaponSkill': 3, 'BallisticSkill': None, 'Strength': 3, 'Toughness': None, 'Initiative': 3, 'Wounds': None, 'Attacks': 1, 'Leadership': None},
        ],
    },
    'Gorebeast Chariot': {
        'url': 'gorebeast-chariot',
        'points': 135,
        'troop_type': 'HeavyChariot',
        'armour_value': '3+',
        'Movement': None,
        'WeaponSkill': None,
        'BallisticSkill': None,
        'Strength': 5,
        'Toughness': 5,
        'Initiative': None,
        'Wounds': 4,
        'Attacks': None,
        'Leadership': None,
        'SpecialRules': ['Armour Bane (1, Gorebeast only)', 'Close Order', 'Ensorcelled Weapons', 'First Charge', 'Impact Hits (D6+2)', 'Killing Blow (Gorebeast only)', 'Mark of Chaos Undivided'],
        'equipment': '- Chaos Charioteers: Hand weapons and halberds\n- Gorebeast: Goring horns (counts as a hand weapon)',
        "profiles": [
            {'Name': 'Chariot', 'Movement': None, 'WeaponSkill': None, 'BallisticSkill': None, 'Strength': 5, 'Toughness': 5, 'Initiative': None, 'Wounds': 4, 'Attacks': None, 'Leadership': None},
            {'Name': 'Chaos Charioteer (x2)', 'Movement': None, 'WeaponSkill': 5, 'BallisticSkill': 3, 'Strength': 4, 'Toughness': None, 'Initiative': 4, 'Wounds': None, 'Attacks': 1, 'Leadership': 8},
            {'Name': 'Gorebeast (x1)', 'Movement': 6, 'WeaponSkill': 4, 'BallisticSkill': None, 'Strength': 5, 'Toughness': None, 'Initiative': 2, 'Wounds': None, 'Attacks': 3, 'Leadership': None},
        ],
    },
    'Great Eagle': {
        'url': 'great-eagle-mount',
        'points': 60,
        'troop_type': 'MonstrousCreature',
        'Movement': 2,
        'WeaponSkill': 5,
        'BallisticSkill': None,
        'Strength': 4,
        'Toughness': '+1',
        'Initiative': 4,
        'Wounds': '+1',
        'Attacks': 3,
        'Leadership': None,
        'SpecialRules': ['Close Order', 'Fear', 'Fly (10)', 'Stomp Attacks (1)', 'Swiftstride'],
        'equipment': 'Wicked claws and serrated maw',
    },
    'Great Stag': {
        'url': 'great-stag',
        'points': 50,
        'troop_type': 'MonstrousCavalry',
        'Movement': 8,
        'WeaponSkill': 4,
        'BallisticSkill': None,
        'Strength': 5,
        'Toughness': '+1',
        'Initiative': 4,
        'Wounds': '+1',
        'Attacks': 2,
        'Leadership': None,
        'SpecialRules': ['Armoured Hide (2)', 'Crown of Antlers', 'Fear', 'First Charge', 'Impact Hits (1)', 'Move Through Cover', 'Stomp Attacks (1)', 'Swiftstride'],
        'equipment': 'Mighty antlers',
    },
    'Great Taurus': {
        'url': 'great-taurus',
        'points': 120,
        'troop_type': 'Behemoth',
        'Movement': 6,
        'WeaponSkill': 5,
        'BallisticSkill': None,
        'Strength': 5,
        'Toughness': None,
        'Initiative': 3,
        'Wounds': '+4',
        'Attacks': 3,
        'Leadership': None,
        'SpecialRules': ['Blazing Body', 'Born of Fire', 'Ward3 (Flaming)', 'Close Order', 'Fly (9)', 'Furious Charge', 'Large Target', 'Stomp Attacks (D3)', 'Swiftstride', 'Terror'],
        'equipment': 'Trampling hooves and goring horns',
    },
    'Griffon (Empire)': {
        'url': 'griffon-empire',
        'points': 130,
        'troop_type': 'MonstrousCreature',
        'Movement': 6,
        'WeaponSkill': 5,
        'BallisticSkill': None,
        'Strength': 5,
        'Toughness': '+1',
        'Initiative': 5,
        'Wounds': '+3',
        'Attacks': 4,
        'Leadership': None,
        'SpecialRules': ['Close Order', 'Fly (9)', 'Large Target', 'Stomp Attacks (D3)', 'Swiftstride', 'Terror'],
        'equipment': 'Wicked claws, serrated maw and griffonic pelt (counts as heavy armour)',
    },
    'Griffon (High Elves)': {
        'url': 'griffon-high-elves',
        'points': 130,
        'troop_type': 'MonstrousCreature',
        'Movement': 6,
        'WeaponSkill': 5,
        'BallisticSkill': None,
        'Strength': 5,
        'Toughness': '+2',
        'Initiative': 5,
        'Wounds': '+3',
        'Attacks': 4,
        'Leadership': None,
        'SpecialRules': ['Close Order', 'Fly (9)', 'Large Target', 'Stomp Attacks (D3)', 'Swiftstride', 'Terror'],
        'equipment': 'Wicked claws, serrated maw and griffonic pelt (counts as heavy armour)',
    },
    'Hippogryph': {
        'url': 'hippogryph',
        'points': 120,
        'troop_type': 'MonstrousCreature',
        'Movement': 7,
        'WeaponSkill': 5,
        'BallisticSkill': None,
        'Strength': 5,
        'Toughness': '+1',
        'Initiative': 5,
        'Wounds': '+3',
        'Attacks': 4,
        'Leadership': None,
        'SpecialRules': ['Close Order', 'Counter Charge', 'Fly (9)', 'Large Target', 'Stomp Attacks (D3)', 'Swiftstride', 'Terror'],
        'equipment': 'Wicked claws, serrated maw and griffonic pelt (counts as heavy armour)',
    },
    'Imperial Griffon': {
        'url': 'imperial-griffon',
        'points': 160,
        'troop_type': 'Behemoth',
        'Movement': 6,
        'WeaponSkill': 5,
        'BallisticSkill': None,
        'Strength': 6,
        'Toughness': '+1',
        'Initiative': 4,
        'Wounds': '+4',
        'Attacks': 4,
        'Leadership': None,
        'SpecialRules': ['Close Order', 'Fly (9)', 'Large Target', 'Stomp Attacks (D3+1)', 'Swiftstride', 'Terror'],
        'equipment': 'Wicked claws, serrated maw and griffonic pelt (counts as heavy armour)',
    },
    'Juggernaut of Khorne': {
        'url': 'juggernaut-of-khorne',
        'points': 50,
        'troop_type': 'MonstrousCavalry',
        'Movement': 7,
        'WeaponSkill': 4,
        'BallisticSkill': None,
        'Strength': 5,
        'Toughness': '+1',
        'Initiative': 2,
        'Wounds': '+1',
        'Attacks': 2,
        'Leadership': None,
        'SpecialRules': ['Armoured Hide (1)', 'Daemonic', 'Daemon of Khorne', 'First Charge', 'Impact Hits (2)', 'Swiftstride'],
        'equipment': 'Brass bound hooves and brazen hide (counts as barding)',
    },
    'Khemrian Warsphinx': {
        'url': 'khemrian-warsphinx',
        'points': 175,
        'troop_type': 'Behemoth',
        'armour_value': '5+',
        'Movement': 6,
        'WeaponSkill': 4,
        'BallisticSkill': None,
        'Strength': 5,
        'Toughness': 6,
        'Initiative': 1,
        'Wounds': 5,
        'Attacks': 4,
        'Leadership': None,
        'SpecialRules': ['Arrows of Asaph', 'Cleaving Blow (Tomb Guard Crew only)', 'Close Order', 'Howdah', 'Indomitable (2)', 'Khopesh (Tomb Guard Crew only)', 'Large Target', 'Nehekharan Undead', 'Regeneration (6+)', 'Stomp Attacks (D3)', 'Terror'],
        'equipment': '- Khemrian Warsphinx: Wicked claws\n- Tomb Guard Crew: Hand weapons, cavalry spears and shortbows',
        "profiles": [
            {'Name': 'Khemrian Warsphinx', 'Movement': 6, 'WeaponSkill': 4, 'BallisticSkill': None, 'Strength': 5, 'Toughness': 6, 'Initiative': 1, 'Wounds': 5, 'Attacks': 4, 'Leadership': None},
            {'Name': 'Tomb Guard Crew (x2)', 'Movement': None, 'WeaponSkill': 3, 'BallisticSkill': 3, 'Strength': 4, 'Toughness': None, 'Initiative': 3, 'Wounds': None, 'Attacks': 1, 'Leadership': 8},
        ],
    },
    'Lammasu': {
        'url': 'lammasu',
        'points': 95,
        'troop_type': 'MonstrousCreature',
        'Movement': 6,
        'WeaponSkill': 4,
        'BallisticSkill': None,
        'Strength': 5,
        'Toughness': None,
        'Initiative': 2,
        'Wounds': '+3',
        'Attacks': 2,
        'Leadership': None,
        'SpecialRules': ['Armour Bane (2)', 'Close Order', 'Fly (9)', 'Furious Charge', 'Large Target', 'Magic Resistance (-3)', 'Sorcerous Miasma', 'Stomp Attacks (D3)', 'Swiftstride', 'Terror'],
        'equipment': 'Claws and fangs (counts as a hand weapon)',
    },
    'Lothern Skycutter': {
        'url': 'lothern-skycutter',
        'points': 90,
        'troop_type': 'HeavyChariot',
        'armour_value': '4+',
        'Movement': None,
        'WeaponSkill': None,
        'BallisticSkill': None,
        'Strength': 5,
        'Toughness': 4,
        'Initiative': None,
        'Wounds': 4,
        'Attacks': None,
        'Leadership': None,
        'SpecialRules': ['Close Order', 'Elven Reflexes (Crew only)', 'Fear', 'Fly (10)', 'Impact Hits (D3+1)', 'Swiftstride', 'Valour of Ages'],
        'equipment': '- Sea Guard Crew: Hand weapons, cavalry spears and shortbows\n- Swiftfeather Roc: Wicked claws',
        "profiles": [
            {'Name': 'Lothern Skycutter', 'Movement': None, 'WeaponSkill': None, 'BallisticSkill': None, 'Strength': 5, 'Toughness': 4, 'Initiative': None, 'Wounds': 4, 'Attacks': None, 'Leadership': None},
            {'Name': 'Sea Guard Crew (x3)', 'Movement': None, 'WeaponSkill': 4, 'BallisticSkill': 4, 'Strength': 3, 'Toughness': None, 'Initiative': 4, 'Wounds': None, 'Attacks': 1, 'Leadership': 8},
            {'Name': 'Swiftfeather Roc (x1)', 'Movement': 2, 'WeaponSkill': 5, 'BallisticSkill': None, 'Strength': 4, 'Toughness': None, 'Initiative': 4, 'Wounds': None, 'Attacks': 2, 'Leadership': None},
        ],
    },
    'Manticore (Dark Elves)': {
        'url': 'manticore-dark-elves',
        'points': 130,
        'troop_type': 'MonstrousCreature',
        'Movement': 6,
        'WeaponSkill': 5,
        'BallisticSkill': None,
        'Strength': 5,
        'Toughness': '+1',
        'Initiative': 5,
        'Wounds': '+4',
        'Attacks': 4,
        'Leadership': None,
        'SpecialRules': ['Close Order', 'Fly (9)', 'Large Target', 'Stomp Attacks (D3)', 'Swiftstride', 'Terror', 'Wilful Beast'],
        'equipment': 'Wicked claws and scaly skin (counts as heavy armour)',
    },
    'Manticore (Warriors of Chaos)': {
        'url': 'manticore-warriors-of-chaos',
        'points': 120,
        'troop_type': 'MonstrousCreature',
        'Movement': 6,
        'WeaponSkill': 5,
        'BallisticSkill': None,
        'Strength': 5,
        'Toughness': None,
        'Initiative': 5,
        'Wounds': '+4',
        'Attacks': 4,
        'Leadership': None,
        'SpecialRules': ['Close Order', 'Fly (9)', 'Large Target', 'Stomp Attacks (D3)', 'Swiftstride', 'Terror', 'Wilful Beast'],
        'equipment': 'Wicked claws and scaly skin (counts as heavy armour)',
    },
    'Moon Dragon': {
        'url': 'moon-dragon',
        'points': 235,
        'troop_type': 'Behemoth',
        'Movement': 6,
        'WeaponSkill': 6,
        'BallisticSkill': None,
        'Strength': 6,
        'Toughness': '+2',
        'Initiative': 3,
        'Wounds': '+5',
        'Attacks': 5,
        'Leadership': None,
        'SpecialRules': ['Close Order', 'Fly (10)', 'Large Target', 'Stomp Attacks (D6)', 'Swiftstride', 'Terror'],
        'equipment': 'Wicked claws, dragon fire and draconic scales (counts as full plate armour)',
    },
    'Mortis Engine': {
        'url': 'mortis-engine',
        'points': 195,
        'troop_type': 'HeavyChariot',
        'armour_value': '4+',
        'Movement': None,
        'WeaponSkill': None,
        'BallisticSkill': None,
        'Strength': 5,
        'Toughness': 5,
        'Initiative': None,
        'Wounds': 5,
        'Attacks': None,
        'Leadership': None,
        'SpecialRules': ['Accursed Reliquary', 'Blasphemous Tome', 'Close Order', 'Dark Vitality', 'First Charge', 'Fly (8)', 'Impact Hits (D6+1)', 'Large Target', 'Necromantic Undead', 'Random Attacks (Spirit Horde only)', 'Regeneration (6+)', 'Wailing Dirge'],
        'equipment': '- Banshees: Hand weapons\n- Spirit Horde: Hand weapons and lances',
        "profiles": [
            {'Name': 'Mortis Engine', 'Movement': None, 'WeaponSkill': None, 'BallisticSkill': None, 'Strength': 5, 'Toughness': 5, 'Initiative': None, 'Wounds': 5, 'Attacks': None, 'Leadership': None},
            {'Name': 'Banshees (x3)', 'Movement': None, 'WeaponSkill': 3, 'BallisticSkill': 0, 'Strength': 3, 'Toughness': None, 'Initiative': 3, 'Wounds': None, 'Attacks': 1, 'Leadership': 5},
            {'Name': 'Spirit Horde', 'Movement': 6, 'WeaponSkill': 3, 'BallisticSkill': 0, 'Strength': 3, 'Toughness': None, 'Initiative': 1, 'Wounds': None, 'Attacks': 'D6', 'Leadership': None},
        ],
    },
    'Necrolith Bone Dragon': {
        'url': 'necrolith-bone-dragon',
        'points': 195,
        'troop_type': 'Behemoth',
        'Movement': 6,
        'WeaponSkill': 4,
        'BallisticSkill': None,
        'Strength': 6,
        'Toughness': '+1',
        'Initiative': 2,
        'Wounds': '+5',
        'Attacks': 5,
        'Leadership': None,
        'SpecialRules': ['Close Order', 'Cloud of Dust', 'Dry as Dust', 'Fly (9)', 'Indomitable (2)', 'Large Target', 'Nehekharan Undead', 'Stomp Attacks (D6)', 'Swiftstride', 'Terror'],
        'equipment': 'Wicked claws, breath of desiccation and draconic bones (counts as full plate armour)',
    },
    'Nightmare': {
        'url': 'nightmare',
        'points': 16,
        'troop_type': 'HeavyCavalry',
        'Movement': 7,
        'WeaponSkill': 3,
        'BallisticSkill': None,
        'Strength': 4,
        'Toughness': None,
        'Initiative': 2,
        'Wounds': None,
        'Attacks': 1,
        'Leadership': None,
        'SpecialRules': ['Counter Charge', 'First Charge', 'Necromantic Undead', 'Swiftstride'],
        'equipment': 'Iron-shod hooves (counts as a hand weapon) and barding',
    },
    'Orc Boar Chariot': {
        'url': 'orc-boar-chariot',
        'points': 90,
        'troop_type': 'HeavyChariot',
        'armour_value': '4+',
        'Movement': None,
        'WeaponSkill': None,
        'BallisticSkill': None,
        'Strength': 5,
        'Toughness': 5,
        'Initiative': None,
        'Wounds': 4,
        'Attacks': None,
        'Leadership': None,
        'SpecialRules': ['Choppas', 'Close Order', 'First Charge', 'Ignore Goblin Panic', 'Impact Hits (D6+1)', 'Impetuous', 'Tusker Charge', 'Warband'],
        'equipment': '- Orc Crew: Hand weapons and cavalry spears\n- War Boars: Tusks (counts as hand weapons)',
        "profiles": [
            {'Name': 'Chariot', 'Movement': None, 'WeaponSkill': None, 'BallisticSkill': None, 'Strength': 5, 'Toughness': 5, 'Initiative': None, 'Wounds': 4, 'Attacks': None, 'Leadership': None},
            {'Name': 'Orc Crew (x2)', 'Movement': None, 'WeaponSkill': 3, 'BallisticSkill': 3, 'Strength': 3, 'Toughness': None, 'Initiative': 3, 'Wounds': None, 'Attacks': 1, 'Leadership': 7},
            {'Name': 'War Boars (x2)', 'Movement': 7, 'WeaponSkill': 3, 'BallisticSkill': None, 'Strength': 3, 'Toughness': None, 'Initiative': 3, 'Wounds': None, 'Attacks': 1, 'Leadership': None},
        ],
    },
    'Palanquin of Nurgle': {
        'url': 'palanquin-of-nurgle',
        'points': 40,
        'troop_type': 'MonstrousCavalry',
        'Movement': 4,
        'WeaponSkill': 3,
        'BallisticSkill': None,
        'Strength': 3,
        'Toughness': None,
        'Initiative': 3,
        'Wounds': '+4',
        'Attacks': 'D6+1',
        'Leadership': None,
        'SpecialRules': ['Daemonic', 'Daemon of Nurgle', 'Poisoned Attacks', 'Random Attacks'],
        'equipment': 'Many grasping claws (counts as a hand weapon)',
    },
    'Pegasus': {
        'url': 'pegasus',
        'points': 30,
        'troop_type': 'MonstrousCavalry',
        'Movement': 8,
        'WeaponSkill': 3,
        'BallisticSkill': None,
        'Strength': 4,
        'Toughness': None,
        'Initiative': 4,
        'Wounds': '+1',
        'Attacks': 2,
        'Leadership': None,
        'SpecialRules': ['Counter Charge', 'First Charge', 'Fly (10)', 'Swiftstride'],
        'equipment': 'Iron-shod hooves (counts as a hand weapon)',
    },
    'Plague Furnace': {
        'url': 'plague-furnace',
        'points': 170,
        'troop_type': 'HeavyChariot',
        'armour_value': '4+',
        'Movement': 2,
        'WeaponSkill': None,
        'BallisticSkill': None,
        'Strength': 5,
        'Toughness': 6,
        'Initiative': None,
        'Wounds': 5,
        'Attacks': None,
        'Leadership': None,
        'SpecialRules': ['Dragged Along', 'Fear', 'Frenzy', 'Great Censer', 'Impact Hits (D3+1)', 'Large Target', 'Magic Resistance (-1)', 'Poisoned Attacks', 'Scurrying Masses', 'Stomp Attacks (D3+1)'],
        'equipment': '- Plague Furnace: Billowing Death\n- Plague Monk Crew: Hand weapon',
        "profiles": [
            {'Name': 'Plague Furnace', 'Movement': 2, 'WeaponSkill': None, 'BallisticSkill': None, 'Strength': 5, 'Toughness': 6, 'Initiative': None, 'Wounds': 5, 'Attacks': None, 'Leadership': None},
            {'Name': 'Plague Monk Crew (x3)', 'Movement': None, 'WeaponSkill': 3, 'BallisticSkill': 0, 'Strength': 3, 'Toughness': None, 'Initiative': 3, 'Wounds': None, 'Attacks': 2, 'Leadership': 5},
        ],
    },
    'Razorgor Chariot': {
        'url': 'razorgor-chariot',
        'points': 120,
        'troop_type': 'HeavyChariot',
        'armour_value': '4+',
        'Movement': None,
        'WeaponSkill': None,
        'BallisticSkill': None,
        'Strength': 5,
        'Toughness': 5,
        'Initiative': None,
        'Wounds': 4,
        'Attacks': None,
        'Leadership': None,
        'SpecialRules': ['Armour Bane (1 Razorgor only)', 'Close Order', 'Fear', 'First Charge', 'Foe Render (Razorgor only)', 'Impact Hits (D6+2)', 'Mark of Chaos Undivided', 'Primal Fury', 'Razor Tusks'],
        'equipment': '- Bestigor Crew: Hand weapon and great weapon\n- Gor Crew:  Hand weapon and cavalry spear\n- Razorgor: Tusks (counts as hand weapon)',
        "profiles": [
            {'Name': 'Chariot', 'Movement': None, 'WeaponSkill': None, 'BallisticSkill': None, 'Strength': 5, 'Toughness': 5, 'Initiative': None, 'Wounds': 4, 'Attacks': None, 'Leadership': None},
            {'Name': 'Bestigor Crew (x1)', 'Movement': None, 'WeaponSkill': 4, 'BallisticSkill': 3, 'Strength': 4, 'Toughness': None, 'Initiative': 4, 'Wounds': None, 'Attacks': 1, 'Leadership': 7},
            {'Name': 'Gor Crew (x1)', 'Movement': None, 'WeaponSkill': 4, 'BallisticSkill': 3, 'Strength': 3, 'Toughness': None, 'Initiative': 3, 'Wounds': None, 'Attacks': 1, 'Leadership': 7},
            {'Name': 'Razorgor (x1)', 'Movement': 7, 'WeaponSkill': 3, 'BallisticSkill': None, 'Strength': 5, 'Toughness': None, 'Initiative': 2, 'Wounds': None, 'Attacks': 4, 'Leadership': None},
        ],
    },
    'Ripperdactyl': {
        'url': 'ripperdactyl',
        'points': 35,
        'troop_type': 'MonstrousCavalry',
        'Movement': 2,
        'WeaponSkill': 3,
        'BallisticSkill': None,
        'Strength': 4,
        'Toughness': '+1',
        'Initiative': 2,
        'Wounds': '+1',
        'Attacks': 2,
        'Leadership': None,
        'SpecialRules': ['Armoured Hide (1)', 'Cleaving Blow (Ripperdactyl only)', 'Fear', 'Fly (9)', 'Furious Charge (Ripperdactyl only)', 'Impetuous', 'Swiftstride', 'Toad Rage'],
        'equipment': 'Claws and teeth (counts as a hand weapon)',
    },
    'Royal Pegasus': {
        'url': 'royal-pegasus',
        'points': 70,
        'troop_type': 'MonstrousCreature',
        'Movement': 8,
        'WeaponSkill': 4,
        'BallisticSkill': None,
        'Strength': 5,
        'Toughness': '+1',
        'Initiative': 5,
        'Wounds': '+1',
        'Attacks': 3,
        'Leadership': None,
        'SpecialRules': ['Armour Bane (1, Royal Pegasus only)', 'Counter Charge', 'First Charge', 'Fly (10)', 'Stomp Attacks (2)', 'Swiftstride'],
        'equipment': 'Iron-shod hooves (counts as a hand weapon) and barding',
    },
    'Scourgerunner Chariot': {
        'url': 'scourgerunner-chariot',
        'points': 85,
        'troop_type': 'LightChariot',
        'armour_value': '5+',
        'Movement': None,
        'WeaponSkill': None,
        'BallisticSkill': None,
        'Strength': 4,
        'Toughness': 4,
        'Initiative': None,
        'Wounds': 4,
        'Attacks': None,
        'Leadership': None,
        'SpecialRules': ['Elven Reflexes', 'Hatred (High Elves)', 'Impact Hits (D6)', 'Open Order', 'Sea Dragon Cloak', 'Swiftstride'],
        'equipment': '- Chariot:  Ravager harpoon\n- Beastmaster Crew: Hand weapons, cavalry spears and repeater crossbows\n- Dark Steeds: Hooves (counts as hand weapons)',
        "profiles": [
            {'Name': 'Chariot', 'Movement': None, 'WeaponSkill': None, 'BallisticSkill': None, 'Strength': 4, 'Toughness': 4, 'Initiative': None, 'Wounds': 4, 'Attacks': None, 'Leadership': None},
            {'Name': 'Beastmaster Crew (x2)', 'Movement': None, 'WeaponSkill': 4, 'BallisticSkill': 4, 'Strength': 3, 'Toughness': None, 'Initiative': 4, 'Wounds': None, 'Attacks': 1, 'Leadership': 8},
            {'Name': 'Dark Steed (x2)', 'Movement': 9, 'WeaponSkill': 3, 'BallisticSkill': None, 'Strength': 3, 'Toughness': None, 'Initiative': 4, 'Wounds': None, 'Attacks': 1, 'Leadership': None},
        ],
    },
    'Screaming Bell': {
        'url': 'screaming-bell',
        'points': 185,
        'troop_type': 'HeavyChariot',
        'armour_value': '4+',
        'Movement': 2,
        'WeaponSkill': None,
        'BallisticSkill': None,
        'Strength': 5,
        'Toughness': 6,
        'Initiative': None,
        'Wounds': 5,
        'Attacks': None,
        'Leadership': None,
        'SpecialRules': ['Armour Bane (2, Rat Ogre only)', 'Blessings of the Horned Rat', 'Dragged Along', 'Impact Hits (D6+1)', 'Large Target', 'Magic Resistance (-3)', 'Scurrying Masses', 'Stubborn', 'Terror', 'Tolling the Bell'],
        'equipment': '- Rat Ogre Crew: Hand weapon',
        "profiles": [
            {'Name': 'Screaming Bell', 'Movement': 2, 'WeaponSkill': None, 'BallisticSkill': None, 'Strength': 5, 'Toughness': 6, 'Initiative': None, 'Wounds': 5, 'Attacks': None, 'Leadership': None},
            {'Name': 'Rat Ogre Crew (x1)', 'Movement': None, 'WeaponSkill': 3, 'BallisticSkill': 0, 'Strength': 5, 'Toughness': None, 'Initiative': 4, 'Wounds': None, 'Attacks': 3, 'Leadership': 5},
        ],
    },
    'Seeker Chariot of Slaanesh': {
        'url': 'seeker-chariot-of-slaanesh',
        'points': 100,
        'troop_type': 'LightChariot',
        'armour_value': '5+',
        'Movement': None,
        'WeaponSkill': None,
        'BallisticSkill': None,
        'Strength': 4,
        'Toughness': 4,
        'Initiative': None,
        'Wounds': 4,
        'Attacks': None,
        'Leadership': None,
        'SpecialRules': ['Armour Bane (1, Steed of Slaanesh only)', 'Counter Charge', 'Daemonic', 'Daemons of Slaanesh', 'First Charge', 'Impact Hits (D3+1)', 'Open Order', 'Poisoned Attacks (Steed of Slaanesh only)', 'Swiftstride'],
        'equipment': '- Daemonette Crew: Piercing claws\n- Steeds of Slaanesh: Claws and fangs (counts as hand weapons)',
        "profiles": [
            {'Name': 'Seeker Chariot', 'Movement': None, 'WeaponSkill': None, 'BallisticSkill': None, 'Strength': 4, 'Toughness': 4, 'Initiative': None, 'Wounds': 4, 'Attacks': None, 'Leadership': None},
            {'Name': 'Daemonette Crew (x2)', 'Movement': None, 'WeaponSkill': 4, 'BallisticSkill': 3, 'Strength': 3, 'Toughness': None, 'Initiative': 5, 'Wounds': None, 'Attacks': 1, 'Leadership': 7},
            {'Name': 'Steed of Slaanesh (x2)', 'Movement': 9, 'WeaponSkill': 3, 'BallisticSkill': None, 'Strength': 3, 'Toughness': None, 'Initiative': 5, 'Wounds': None, 'Attacks': 1, 'Leadership': None},
        ],
    },
    'Skeletal Steed (Tomb Kings)': {
        'url': 'skeletal-steed-tomb-kings',
        'points': 12,
        'troop_type': 'HeavyCavalry',
        'Movement': 8,
        'WeaponSkill': 2,
        'BallisticSkill': None,
        'Strength': 3,
        'Toughness': None,
        'Initiative': 2,
        'Wounds': None,
        'Attacks': 1,
        'Leadership': None,
        'SpecialRules': ['Nehekharan Undead', 'Swiftstride', 'Vanguard'],
        'equipment': 'Skeletal hooves (counts as hand weapon)',
    },
    'Skeletal Steed (Vampire Counts)': {
        'url': 'skeletal-steed-vampire-counts',
        'points': 14,
        'troop_type': 'HeavyCavalry',
        'Movement': 7,
        'WeaponSkill': 2,
        'BallisticSkill': None,
        'Strength': 3,
        'Toughness': None,
        'Initiative': 2,
        'Wounds': None,
        'Attacks': 1,
        'Leadership': None,
        'SpecialRules': ['First Charge', 'Necromantic Undead', 'Swiftstride'],
        'equipment': 'Skeletal hooves (counts as hand weapon) and barding',
    },
    'Skeleton Chariot': {
        'url': 'skeleton-chariot',
        'points': 35,
        'troop_type': 'LightChariot',
        'armour_value': '5+',
        'Movement': None,
        'WeaponSkill': None,
        'BallisticSkill': None,
        'Strength': 4,
        'Toughness': 4,
        'Initiative': None,
        'Wounds': 3,
        'Attacks': None,
        'Leadership': None,
        'SpecialRules': ['Dry as Dust', 'Impact Hits (D3)', 'Nehekharan Undead', 'Open Order', 'Reserve Move', 'Swiftstride'],
        'equipment': '- Skeletal Steed: Skeletal hooves (counts as hand weapons)',
        "profiles": [
            {'Name': 'Chariot', 'Movement': None, 'WeaponSkill': None, 'BallisticSkill': None, 'Strength': 4, 'Toughness': 4, 'Initiative': None, 'Wounds': 3, 'Attacks': None, 'Leadership': None},
            {'Name': 'Skeletal Steed (x2)', 'Movement': 8, 'WeaponSkill': 2, 'BallisticSkill': None, 'Strength': 3, 'Toughness': None, 'Initiative': 2, 'Wounds': None, 'Attacks': 1, 'Leadership': None},
        ],
    },
    'Sky Lantern': {
        'url': 'sky-lantern',
        'points': 135,
        'troop_type': 'HeavyChariot',
        'armour_value': '4+',
        'Movement': 1,
        'WeaponSkill': None,
        'BallisticSkill': None,
        'Strength': 5,
        'Toughness': 4,
        'Initiative': None,
        'Wounds': 7,
        'Attacks': None,
        'Leadership': None,
        'SpecialRules': ['Close Order', 'Disengage', 'Eye of the Dragon', 'Feigned Flight', 'Fire & Flee', 'Flammable', 'Fly (8)', 'Heavenly Beacon', 'Impact Hits (D3+1, Sky Lantern only)', 'Large Target', 'Reserve Move', 'Scouts'],
        'equipment': '- Lantern Gunners: Hand weapons\n- Commander: Hand weapon',
        "profiles": [
            {'Name': 'Sky Lantern', 'Movement': 1, 'WeaponSkill': None, 'BallisticSkill': None, 'Strength': 5, 'Toughness': 4, 'Initiative': None, 'Wounds': 7, 'Attacks': None, 'Leadership': None},
            {'Name': 'Lantern Gunners (x4)', 'Movement': None, 'WeaponSkill': 3, 'BallisticSkill': 4, 'Strength': 3, 'Toughness': None, 'Initiative': 3, 'Wounds': None, 'Attacks': 1, 'Leadership': 8},
            {'Name': 'Commander (x1)', 'Movement': None, 'WeaponSkill': 3, 'BallisticSkill': 5, 'Strength': 3, 'Toughness': None, 'Initiative': 3, 'Wounds': None, 'Attacks': 2, 'Leadership': 8},
        ],
    },
    'Star Dragon': {
        'url': 'star-dragon',
        'points': 290,
        'troop_type': 'Behemoth',
        'Movement': 6,
        'WeaponSkill': 7,
        'BallisticSkill': None,
        'Strength': 7,
        'Toughness': '+3',
        'Initiative': 2,
        'Wounds': '+6',
        'Attacks': 6,
        'Leadership': None,
        'SpecialRules': ['Close Order', 'Fly (10)', 'Large Target', 'Stomp Attacks (D6+1)', 'Swiftstride', 'Terror'],
        'equipment': 'Wicked claws, dragon fire and draconic scales (counts as full plate armour)',
    },
    'Steed of Slaanesh': {
        'url': 'steed-of-slaanesh',
        'points': 16,
        'troop_type': 'LightCavalry',
        'Movement': 9,
        'WeaponSkill': 3,
        'BallisticSkill': None,
        'Strength': 3,
        'Toughness': None,
        'Initiative': 5,
        'Wounds': None,
        'Attacks': 1,
        'Leadership': None,
        'SpecialRules': ['Armour Bane (1, Steed of Slaanesh only)', 'Counter Charge', 'Daemonic', 'Daemon of Slaanesh', 'Fast Cavalry', 'Poisoned Attacks (Steed of Slaanesh only)', 'Swiftstride'],
        'equipment': 'Claws and fangs (counts as a hand weapon)',
    },
    'Stegadon': {
        'url': 'stegadon',
        'points': 215,
        'troop_type': 'Behemoth',
        'armour_value': '4+',
        'Movement': 6,
        'WeaponSkill': 3,
        'BallisticSkill': None,
        'Strength': 5,
        'Toughness': 6,
        'Initiative': 2,
        'Wounds': 5,
        'Attacks': 4,
        'Leadership': None,
        'SpecialRules': ['Close Order', 'Cold Blooded', 'Howdah', 'Immune to Psychology', 'Impact Hits (D3+1)', 'Large Target', 'Poisoned Attacks (javelins only)', 'Stomp Attacks (D3+2)', 'Stubborn', 'Terror'],
        'equipment': '- Stegadon: Great horns and giant bow\n- Skink Crew: Hand weapons and javelins',
        "profiles": [
            {'Name': 'Stegadon', 'Movement': 6, 'WeaponSkill': 3, 'BallisticSkill': None, 'Strength': 5, 'Toughness': 6, 'Initiative': 2, 'Wounds': 5, 'Attacks': 4, 'Leadership': None},
            {'Name': 'Skink Crew (x5)', 'Movement': None, 'WeaponSkill': 2, 'BallisticSkill': 3, 'Strength': 3, 'Toughness': None, 'Initiative': 4, 'Wounds': None, 'Attacks': 1, 'Leadership': 6},
        ],
    },
    'Stonehorn': {
        'url': 'stonehorn',
        'points': 195,
        'troop_type': 'Behemoth',
        'Movement': 7,
        'WeaponSkill': 3,
        'BallisticSkill': None,
        'Strength': 6,
        'Toughness': '+1',
        'Initiative': 2,
        'Wounds': '+4',
        'Attacks': 4,
        'Leadership': None,
        'SpecialRules': ['Armour Bane (2, Stonehorn only)', 'Close Order', 'First Charge', 'Impact Hits (D6+1)', 'Large Target', 'Stone Skeleton', 'Swiftstride', 'Terror', 'Thunderous Charge'],
        'equipment': 'Horns of stone and petrified flesh (counts as full plate armour)',
    },
    'Terradon': {
        'url': 'terradon',
        'points': 30,
        'troop_type': 'MonstrousCavalry',
        'Movement': 2,
        'WeaponSkill': 3,
        'BallisticSkill': None,
        'Strength': 4,
        'Toughness': '+1',
        'Initiative': 2,
        'Wounds': '+1',
        'Attacks': 1,
        'Leadership': None,
        'SpecialRules': ['Armoured Hide (1)', 'Drop Rocks', 'Fear', 'Fly (10)', 'Swiftstride'],
        'equipment': 'Claws and teeth (counts as a hand weapon)',
    },
    'Terrorgheist': {
        'url': 'terrorgheist-mount',
        'points': 185,
        'troop_type': 'Behemoth',
        'Movement': 6,
        'WeaponSkill': 3,
        'BallisticSkill': None,
        'Strength': 5,
        'Toughness': '+1',
        'Initiative': 3,
        'Wounds': '+5',
        'Attacks': 4,
        'Leadership': None,
        'SpecialRules': ['Close Order', 'Fly (9)', 'Indomitable (1)', 'Infested', 'Large Target', 'Necromantic Undead', 'Regeneration (5+)', 'Stomp Attacks (D6)', 'Swiftstride', 'Terror', 'Wailing Dirge'],
        'equipment': 'Filth-encrusted talons, rancid maw and calloused hide (counts as light armour)',
    },
    'Thundertusk': {
        'url': 'thundertusk',
        'points': 165,
        'troop_type': 'Behemoth',
        'Movement': 6,
        'WeaponSkill': 3,
        'BallisticSkill': None,
        'Strength': 6,
        'Toughness': '+1',
        'Initiative': 2,
        'Wounds': '+4',
        'Attacks': 4,
        'Leadership': None,
        'SpecialRules': ['Close Order', 'First Charge', 'Impact Hits (D3)', 'Large Target', 'Numbing Chill', 'Stomp Attacks (3)', 'Swiftstride', 'Terror'],
        'equipment': 'Great tusks, chill breath and frozen pelt (counts as heavy armour)',
    },
    'Tiranoc Chariot': {
        'url': 'tiranoc-chariot',
        'points': 75,
        'troop_type': 'LightChariot',
        'armour_value': '5+',
        'Movement': None,
        'WeaponSkill': None,
        'BallisticSkill': None,
        'Strength': 5,
        'Toughness': 4,
        'Initiative': None,
        'Wounds': 4,
        'Attacks': None,
        'Leadership': None,
        'SpecialRules': ['Elven Reflexes', 'Impact Hits (D6)', 'Open Order', 'Quick Shot', 'Swiftstride', 'Valour of Ages'],
        'equipment': '- Tiranoc Charioteers: Hand weapons, cavalry spears and longbows\n- Elven Steeds: Hooves (counts as a hand weapon)',
        "profiles": [
            {'Name': 'Tiranoc Chariot', 'Movement': None, 'WeaponSkill': None, 'BallisticSkill': None, 'Strength': 5, 'Toughness': 4, 'Initiative': None, 'Wounds': 4, 'Attacks': None, 'Leadership': None},
            {'Name': 'Tiranoc Charioteer (x2)', 'Movement': None, 'WeaponSkill': 4, 'BallisticSkill': 4, 'Strength': 3, 'Toughness': None, 'Initiative': 4, 'Wounds': None, 'Attacks': 1, 'Leadership': 8},
            {'Name': 'Elven Steed (x2)', 'Movement': 9, 'WeaponSkill': 3, 'BallisticSkill': None, 'Strength': 3, 'Toughness': None, 'Initiative': 4, 'Wounds': None, 'Attacks': 1, 'Leadership': None},
        ],
    },
    'Tuskgor Chariot': {
        'url': 'tuskgor-chariot',
        'points': 85,
        'troop_type': 'HeavyChariot',
        'armour_value': '4+',
        'Movement': None,
        'WeaponSkill': None,
        'BallisticSkill': None,
        'Strength': 5,
        'Toughness': 4,
        'Initiative': None,
        'Wounds': 4,
        'Attacks': None,
        'Leadership': None,
        'SpecialRules': ['Close Order', 'First Charge', 'Impact Hits (D6+1)', 'Mark of Chaos Undivided', 'Primal Fury', 'Razor Tusks', 'Warband'],
        'equipment': '- Bestigor Crew: Hand weapon and great weapon\n- Gor Crew:  Hand weapon and cavalry spear\n- Tuskgors: Tusks (counts as hand weapon)',
        "profiles": [
            {'Name': 'Chariot', 'Movement': None, 'WeaponSkill': None, 'BallisticSkill': None, 'Strength': 5, 'Toughness': 4, 'Initiative': None, 'Wounds': 4, 'Attacks': None, 'Leadership': None},
            {'Name': 'Bestigor Crew (x1)', 'Movement': None, 'WeaponSkill': 4, 'BallisticSkill': 3, 'Strength': 4, 'Toughness': None, 'Initiative': 4, 'Wounds': None, 'Attacks': 1, 'Leadership': 7},
            {'Name': 'Gor Crew (x1)', 'Movement': None, 'WeaponSkill': 4, 'BallisticSkill': 3, 'Strength': 3, 'Toughness': None, 'Initiative': 3, 'Wounds': None, 'Attacks': 1, 'Leadership': 7},
            {'Name': 'Tuskgor (x2)', 'Movement': 7, 'WeaponSkill': 3, 'BallisticSkill': None, 'Strength': 4, 'Toughness': None, 'Initiative': 2, 'Wounds': None, 'Attacks': 1, 'Leadership': None},
        ],
    },
    'Unicorn': {
        'url': 'unicorn',
        'points': 35,
        'troop_type': 'MonstrousCavalry',
        'Movement': 10,
        'WeaponSkill': 4,
        'BallisticSkill': None,
        'Strength': 4,
        'Toughness': None,
        'Initiative': 5,
        'Wounds': '+1',
        'Attacks': 2,
        'Leadership': None,
        'SpecialRules': ['Armour Bane (2, Unicorn only)', 'Armoured Hide (1)', 'Beguiling Aura', 'Counter Charge', 'Magical Attacks', 'Stomp Attacks (1)', 'Swiftstride'],
        'equipment': 'Hooves and horn (counts as a hand weapon)',
    },
    'War Altar of Sigmar': {
        'url': 'war-altar-of-sigmar',
        'points': 135,
        'troop_type': 'HeavyChariot',
        'armour_value': '4+',
        'Movement': None,
        'WeaponSkill': None,
        'BallisticSkill': None,
        'Strength': 5,
        'Toughness': 5,
        'Initiative': None,
        'Wounds': 5,
        'Attacks': None,
        'Leadership': None,
        'SpecialRules': ['Close Order', 'First Charge', 'Holy Fervour', 'Impact Hits (D6+1)', 'Large Target', 'Magic Resistance (-2)', 'Stubborn', 'Symbol of Might', 'Terror', 'Witch Bane'],
        'equipment': '- Warhorses: Iron-shod hooves (counts as a hand weapon)',
        "profiles": [
            {'Name': 'War Altar', 'Movement': None, 'WeaponSkill': None, 'BallisticSkill': None, 'Strength': 5, 'Toughness': 5, 'Initiative': None, 'Wounds': 5, 'Attacks': None, 'Leadership': None},
            {'Name': 'Barded Warhorse (x2)', 'Movement': 7, 'WeaponSkill': 3, 'BallisticSkill': None, 'Strength': 3, 'Toughness': None, 'Initiative': 3, 'Wounds': None, 'Attacks': 1, 'Leadership': None},
        ],
    },
    'War Boar': {
        'url': 'war-boar',
        'points': 16,
        'troop_type': 'HeavyCavalry',
        'Movement': 7,
        'WeaponSkill': 3,
        'BallisticSkill': None,
        'Strength': 3,
        'Toughness': None,
        'Initiative': 3,
        'Wounds': None,
        'Attacks': 1,
        'Leadership': None,
        'SpecialRules': ['Armoured Hide (1)', 'Counter Charge', 'Swiftstride', 'Tusker Charge'],
        'equipment': 'Tusks (counts as a hand weapon)',
    },
    'Warhawk': {
        'url': 'warhawk',
        'points': 30,
        'troop_type': 'MonstrousCavalry',
        'Movement': 2,
        'WeaponSkill': 3,
        'BallisticSkill': None,
        'Strength': 4,
        'Toughness': '+1',
        'Initiative': 4,
        'Wounds': None,
        'Attacks': 2,
        'Leadership': None,
        'SpecialRules': ['Evasive', 'Fear', 'Feigned Flight', 'Fly (10)', 'Swiftstride'],
        'equipment': 'Wicked claws',
    },
    'Warhorse (Bretonnia)': {
        'url': 'warhorse-bretonnia',
        'points': 12,
        'troop_type': 'LightCavalry',
        'Movement': 8,
        'WeaponSkill': 3,
        'BallisticSkill': None,
        'Strength': 3,
        'Toughness': None,
        'Initiative': 3,
        'Wounds': None,
        'Attacks': 1,
        'Leadership': None,
        'SpecialRules': ['Fast Cavalry', 'Swiftstride'],
        'equipment': 'Iron-shod hooves (counts as a hand weapon)',
    },
    'Warhorse (Realms of Men)': {
        'url': 'warhorse-realms-of-men',
        'points': 12,
        'troop_type': 'LightCavalry',
        'Movement': 8,
        'WeaponSkill': 3,
        'BallisticSkill': None,
        'Strength': 3,
        'Toughness': None,
        'Initiative': 3,
        'Wounds': None,
        'Attacks': 1,
        'Leadership': None,
        'SpecialRules': ['Counter Charge', 'First Charge', 'Swiftstride'],
        'equipment': 'Iron-shod hooves (counts as a hand weapon)',
    },
    'Warhorse (Warriors of Chaos)': {
        'url': 'warhorse-warriors-of-chaos',
        'points': 14,
        'troop_type': 'LightCavalry',
        'Movement': 8,
        'WeaponSkill': 3,
        'BallisticSkill': None,
        'Strength': 3,
        'Toughness': None,
        'Initiative': 3,
        'Wounds': None,
        'Attacks': 1,
        'Leadership': None,
        'SpecialRules': ['Counter Charge', 'Fast Cavalry', 'Swiftstride'],
        'equipment': 'Iron-shod hooves (counts as a hand weapon)',
    },
    'Wyvern': {
        'url': 'wyvern',
        'points': 130,
        'troop_type': 'MonstrousCreature',
        'Movement': 4,
        'WeaponSkill': 5,
        'BallisticSkill': None,
        'Strength': 6,
        'Toughness': '+1',
        'Initiative': 3,
        'Wounds': '+4',
        'Attacks': 3,
        'Leadership': None,
        'SpecialRules': ['Close Order', 'Fly (9)', 'Large Target', 'Stomp Attacks (D3)', 'Swiftstride', 'Terror'],
        'equipment': 'Wicked claws, venomous tail and scaly skin (counts as heavy armour)',
    },
    'Zombie Dragon': {
        'url': 'zombie-dragon',
        'points': 215,
        'troop_type': 'Behemoth',
        'Movement': 6,
        'WeaponSkill': 4,
        'BallisticSkill': None,
        'Strength': 6,
        'Toughness': '+1',
        'Initiative': 2,
        'Wounds': '+5',
        'Attacks': 5,
        'Leadership': None,
        'SpecialRules': ['Carrion Feeders', 'Close Order', 'Fly (9)', 'Large Target', 'Necromantic Undead', 'Stomp Attacks (D6)', 'Swiftstride', 'Terror'],
        'equipment': 'Wicked claws, pestilential breath and draconic scales (counts as full plate armour)',
    },

    # Listed as mounts on their army page. The High Elf ones need an Elven
    # Honour (see HONOUR_MOUNTS); Shieldbearers carry a Dwarf King or Thane.
    'Flamespyre Phoenix': {
        'url': 'flamespyre-phoenix-mount',
        'points': 170,
        'troop_type': 'MonstrousCreature',
        'Movement': 2,
        'WeaponSkill': 5,
        'BallisticSkill': None,
        'Strength': 5,
        'Toughness': '+2',
        'Initiative': 4,
        'Wounds': '+3',
        'Attacks': 3,
        'Leadership': None,
        'SpecialRules': ['Blessings of Asuryan', 'Close Order', 'Fear', 'Flaming Attacks', 'Fly (10)', 'From the Ashes', 'Large Target', 'Stomp Attacks (2)', 'Swiftstride', 'Wake of Fire'],
        'equipment': 'Wicked claws and blazing plumage (counts as heavy armour)',
    },
    'Frostheart Phoenix': {
        'url': 'frostheart-phoenix-mount',
        'points': 205,
        'troop_type': 'MonstrousCreature',
        'Movement': 2,
        'WeaponSkill': 6,
        'BallisticSkill': None,
        'Strength': 6,
        'Toughness': '+3',
        'Initiative': 3,
        'Wounds': '+3',
        'Attacks': 4,
        'Leadership': None,
        'SpecialRules': ['Blizzard Aura', 'Close Order', 'Fear', 'Fly (9)', 'Large Target', 'Stomp Attacks (2)', 'Swiftstride'],
        'equipment': 'Wicked claws and frozen plumage (counts as full plate armour)',
    },
    'Lion Chariot of Chrace': {
        'url': 'lion-chariot-of-chrace',
        'points': 75,
        'troop_type': 'HeavyChariot',
        'armour_value': '4+',
        'Movement': None,
        'WeaponSkill': None,
        'BallisticSkill': None,
        'Strength': 5,
        'Toughness': 4,
        'Initiative': None,
        'Wounds': 4,
        'Attacks': None,
        'Leadership': None,
        'SpecialRules': ['Close Order', 'Elven Reflexes', 'Fear', 'First Charge', 'Impact Hits (D6)', 'Lion Cloak', 'Stubborn', 'Valour of Ages'],
        'equipment': '- Lion Charioteers: Hand weapons and Chracian great blades\n- War Lions: Claws and fangs (counts as a hand weapon)',
        "profiles": [
            {'Name': 'Lion Chariot', 'Movement': None, 'WeaponSkill': None, 'BallisticSkill': None, 'Strength': 5, 'Toughness': 4, 'Initiative': None, 'Wounds': 4, 'Attacks': None, 'Leadership': None},
            {'Name': 'Lion Charioteer (x2)', 'Movement': None, 'WeaponSkill': 5, 'BallisticSkill': 4, 'Strength': 4, 'Toughness': None, 'Initiative': 4, 'Wounds': None, 'Attacks': 1, 'Leadership': 8},
            {'Name': 'War Lion (x2)', 'Movement': 8, 'WeaponSkill': 5, 'BallisticSkill': None, 'Strength': 4, 'Toughness': None, 'Initiative': 4, 'Wounds': None, 'Attacks': 2, 'Leadership': None},
        ],
    },
    'Shieldbearers': {
        'url': 'shieldbearers',
        'points': None,
        'troop_type': 'HeavyInfantry',
        'Movement': 3,
        'WeaponSkill': 5,
        'BallisticSkill': None,
        'Strength': 4,
        'Toughness': None,
        'Initiative': 2,
        'Wounds': '+3',
        'Attacks': 3,
        'Leadership': None,
        'SpecialRules': ['Borne Aloft', 'Gromril Weapons', 'Hatred (Orcs & Goblins)', 'Resolute'],
        'equipment': 'Hand weapon',
    },

    # Mounts with no page of their own: read off their rider's page.
    "Chaos Warhound": {
        "url": "chaos-warhound-handler", "points": 15, "troop_type": "WarBeast",
        "Movement": 7, "WeaponSkill": 4, "BallisticSkill": 0,
        "Strength": 3, "Toughness": 3, "Initiative": 3, "Wounds": 1,
        "Attacks": 1, "Leadership": 6,
        "SpecialRules": ["Armoured Hide (1)", "Loner", "Move Through Cover",
                         "Open Order", "Poisoned Attacks", "Swiftstride",
                         "Vanguard"],
        "note": "Its claws and fangs count as a hand weapon.",
    },
    "Chompa": {
        "url": "kiknik-toofsnatcha", "points": 0, "troop_type": "LightCavalry",
        "Movement": 9, "WeaponSkill": 3, "BallisticSkill": None,
        "Strength": 4, "Toughness": None, "Initiative": 3, "Wounds": None,
        "Attacks": 2, "Leadership": None,
        "SpecialRules": ["Armour Bane (1)"],
        "note": ("Kiknik Toofsnatcha's giant wolf; part of his fixed profile "
                 "rather than an option. Its claws and fangs count as a hand "
                 "weapon."),
    },
    'Sun Dragon': {
        'url': 'sun-dragon',
        'points': 180,
        'troop_type': 'Behemoth',
        'Movement': 6,
        'WeaponSkill': 5,
        'BallisticSkill': None,
        'Strength': 5,
        'Toughness': '+2',
        'Initiative': 4,
        'Wounds': '+4',
        'Attacks': 4,
        'Leadership': None,
        'SpecialRules': ['Close Order', 'Fly (10)', 'Impetuous', 'Large Target', 'Stomp Attacks (D6)', 'Swiftstride', 'Terror'],
        'equipment': 'Wicked claws, dragon fire and draconic scales (counts as full plate armour)',
        'note': "The Dragon Mage's statline already includes its bonuses.",
    },
    # Mounts that are part of their rider's own profile (see mounted.INTEGRAL_MOUNTS).
    'Great Spirit Longma': {
        'url': 'shugengan-lord',
        'points': 0,
        'troop_type': 'MonstrousCreature',
        'Movement': 8,
        'WeaponSkill': 5,
        'BallisticSkill': None,
        'Strength': 5,
        'Toughness': None,
        'Initiative': 4,
        'Wounds': None,
        'Attacks': 3,
        'Leadership': None,
        'SpecialRules': [],
        'equipment': 'Crown of horns',
        'integral': True,
        'note': "Part of its rider's own profile; the rider's statline already includes it.",
    },
    'Ariandir': {
        'url': 'lady-elisse-duchaard',
        'points': 0,
        'troop_type': 'MonstrousCavalry',
        'Movement': 10,
        'WeaponSkill': 4,
        'BallisticSkill': None,
        'Strength': 4,
        'Toughness': None,
        'Initiative': 5,
        'Wounds': None,
        'Attacks': 2,
        'Leadership': None,
        'SpecialRules': [],
        'equipment': 'Hooves and horn (counts as a hand weapon)',
        'integral': True,
        'note': "Part of its rider's own profile; the rider's statline already includes it.",
    },
    'The Shadow Steed': {
        'url': 'the-green-knight',
        'points': 0,
        'troop_type': 'HeavyCavalry',
        'Movement': 8,
        'WeaponSkill': 4,
        'BallisticSkill': None,
        'Strength': 4,
        'Toughness': None,
        'Initiative': 4,
        'Wounds': None,
        'Attacks': 1,
        'Leadership': None,
        'SpecialRules': [],
        'equipment': 'Iron-shod hooves (counts as a hand weapon) and barding',
        'integral': True,
        'note': "Part of its rider's own profile; the rider's statline already includes it.",
    },
    'Chariot of the Gods': {
        'url': 'settra-the-imperishable',
        'points': 0,
        'troop_type': 'HeavyChariot',
        'Movement': None,
        'WeaponSkill': None,
        'BallisticSkill': None,
        'Strength': 5,
        'Toughness': 5,
        'Initiative': None,
        'Wounds': 8,
        'Attacks': None,
        'Leadership': None,
        'SpecialRules': [],
        'equipment': 'Skeletal hooves (counts as Hand weapons)',
        "profiles": [
            {'Name': 'Chariot of the Gods', 'Movement': None, 'WeaponSkill': None, 'BallisticSkill': None, 'Strength': 5, 'Toughness': 5, 'Initiative': None, 'Wounds': 8, 'Attacks': None, 'Leadership': None},
            {'Name': 'Skeletal Steed (x4)', 'Movement': 8, 'WeaponSkill': 2, 'BallisticSkill': None, 'Strength': 3, 'Toughness': None, 'Initiative': 2, 'Wounds': None, 'Attacks': 1, 'Leadership': None},
        ],
        'integral': True,
        'note': "Part of its rider's own profile; the rider's statline already includes it.",
    },

}


# Mounts a High Elf character may only take with a particular Elven Honour.
HONOUR_MOUNTS = {
    "Lion Chariot of Chrace": "Chracian Hunter",
    "Lothern Skycutter": "Sea Guard",
    "Sun Dragon": "Blood of Caledor",
    "Flamespyre Phoenix": "Anointed of Asuryan",
    "Frostheart Phoenix": "Anointed of Asuryan",
}


def get_mount(name):
    """Return a mount's profile by name, or None if it is not recorded."""
    return Mounts.get(name)


def unverified_mounts():
    """Mounts whose own page has not been read; recorded from a rider's entry."""
    return sorted(k for k, v in Mounts.items() if not v.get("verified", True))


def missing_mounts(faction_profiles):
    """Mount names referenced by profiles that have no entry in `Mounts`.

    Every faction lists its mounts in `mount_options`; this reports which of
    those still need their characteristics transcribed.
    """
    referenced = set()
    for profiles in faction_profiles.values():
        for entry in profiles.values():
            referenced.update(entry.get("mount_options", {}).get("mounts", []))
    return sorted(referenced - set(Mounts))
