"""Magic items, runes and abilities: the data, buying them, and their effects.

Every item on the site is recorded (magic_items_data.py, generated by
tools/transcribe_items.py) with a status saying how much of it the engine
models. These tests hold the data to that status, sweep every item a faction
can buy through a real duel, and pin the effects of items whose wording is
easy to misread.
"""

from __future__ import annotations

import io
import unittest
from contextlib import redirect_stdout

from support import FULL, build, fighter

import dice
import rule_catalogue as rc
from combat_simulations import combat_simulation
from faction_profiles import FactionProfiles
from item_allowances import ALLOWANCES
from magic_items import (
    ITEM_STATUSES,
    MagicItemDict,
    allowance_for,
    check_purchase,
    get_magic_item,
    item_budget,
    items_for,
)
from magic_items_data import SITE_ITEMS, SITE_ITEM_WEAPONS
from special_rules import parse_ward
from weapons import find_weapon_key, get_weapon_stats


class TestItemData(unittest.TestCase):
    def test_every_site_item_is_recorded(self):
        for name in SITE_ITEMS:
            with self.subTest(item=name):
                self.assertIsNotNone(get_magic_item(name))

    def test_every_item_has_a_known_status(self):
        for name, entry in MagicItemDict.items():
            with self.subTest(item=name):
                self.assertIn(entry.get("status"), ITEM_STATUSES)

    def test_generated_effects_are_all_things_the_engine_reads(self):
        for name, entry in SITE_ITEMS.items():
            for rule in entry.get("rules", []):
                with self.subTest(item=name, rule=rule):
                    self.assertTrue(rc.engine_reads(rule))

    def test_an_item_with_no_effect_carries_none(self):
        for name, entry in SITE_ITEMS.items():
            if entry["status"] in ("no duel effect", "not modelled"):
                with self.subTest(item=name):
                    self.assertFalse(entry.get("rules") or entry.get("stat_mods")
                                     or entry.get("armour") or entry.get("shield"))

    def test_partial_and_unmodelled_items_say_what_is_missing(self):
        for name, entry in SITE_ITEMS.items():
            if entry["status"] in ("partial", "not modelled"):
                with self.subTest(item=name):
                    self.assertTrue(entry.get("not_modelled"))

    def test_every_magic_weapon_has_a_profile(self):
        for name, entry in MagicItemDict.items():
            if entry.get("is_weapon") and not entry.get("ranged"):
                with self.subTest(item=name):
                    self.assertIsNotNone(find_weapon_key(entry.get("weapon", name)))

    def test_site_weapon_profiles_are_well_formed(self):
        for name, (bonus, ap, rules) in SITE_ITEM_WEAPONS.items():
            with self.subTest(weapon=name):
                self.assertTrue(bonus is None or isinstance(bonus, int))
                self.assertLessEqual(ap, 0)
                self.assertIn("Magical Attacks", rules)

    def test_items_are_sold_to_their_own_army_only(self):
        self.assertIn("Runefang", items_for("Empire of Man"))
        self.assertNotIn("Runefang", items_for("Orc & Goblin Tribes"))
        self.assertIn("Sword of Might", items_for("Orc & Goblin Tribes"))  # common

    def test_named_characters_personal_items_are_not_for_sale(self):
        for faction in FactionProfiles:
            with self.subTest(faction=faction):
                for_sale = set(items_for(faction))
                self.assertNotIn("Chayal", for_sale)
                self.assertNotIn("Bog-wood Staff", for_sale)

    def test_every_allowance_names_a_known_character_and_budget(self):
        budgets = {item_budget(n) for n in MagicItemDict} - {None}
        for faction, profiles in ALLOWANCES.items():
            for profile, allowance in profiles.items():
                with self.subTest(profile=profile):
                    self.assertIn(profile, FactionProfiles[faction])
                    self.assertTrue(set(allowance) <= budgets, allowance)


class TestEveryItemInADuel(unittest.TestCase):
    """Each purchasable item, on a character allowed to buy it, fights a duel."""

    def buyer(self, faction, name):
        """The first character of the faction that may buy this item alone."""
        for profile in sorted(ALLOWANCES.get(faction, {})):
            try:
                check_purchase(faction, profile, [name])
            except ValueError:
                continue
            return profile
        return None

    def test_every_affordable_item_builds_and_fights(self):
        dice.seed(5)
        tried = 0
        for faction in sorted(FactionProfiles):
            names = items_for(faction)
            for name in names if FULL else names[::3]:
                profile = self.buyer(faction, name)
                if profile is None:
                    continue
                with self.subTest(faction=faction, item=name, profile=profile):
                    try:
                        hero = build(faction, profile, name="Buyer", magic_items=[name])
                    except ValueError as exc:
                        # Only an honest kit clash may stop a purchase.
                        self.assertRegex(str(exc), "requires two hands|cannot use a shield")
                        continue
                    tried += 1
                    foe = build(faction, profile, name="Foe")
                    with redirect_stdout(io.StringIO()):
                        winner = combat_simulation(hero, foe, rounds=3, verbose=False)
                    self.assertIn(winner, (hero, foe, None))
                    self.assertLessEqual(hero.current_wounds, hero.Wounds)
                    for stat in ("WeaponSkill", "Strength", "Toughness", "Initiative", "Attacks"):
                        value = getattr(hero, stat)
                        self.assertTrue(value is None or 1 <= value <= 10, (stat, value))
        self.assertGreater(tried, 100)


class TestBuying(unittest.TestCase):
    def test_a_legal_purchase_equips_the_weapon_and_applies_the_rest(self):
        general = build("Empire of Man", "General of the Empire",
                        magic_items=["Sword of Might", "Talisman of Protection"])
        self.assertEqual(general.Weapon, "Sword of Might")
        self.assertIn("Ward5", general.SpecialRules)
        self.assertEqual(general.magic_items, ["Sword of Might", "Talisman of Protection"])

    def test_the_points_allowance_is_enforced(self):
        with self.assertRaisesRegex(ValueError, "may spend 50 points"):
            build("Empire of Man", "Captain of the Empire", magic_items=["Runefang"])

    def test_another_armys_item_is_refused(self):
        with self.assertRaisesRegex(ValueError, "not available"):
            build("Orc & Goblin Tribes", "Orc Warboss", magic_items=["Runefang"])

    def test_two_items_of_one_type_are_refused(self):
        with self.assertRaisesRegex(ValueError, "cannot carry both"):
            check_purchase("Empire of Man", "General of the Empire",
                           ["Sword of Might", "Burning Blade"])

    def test_armour_worn_with_other_armour_does_not_take_the_slot(self):
        check_purchase("High Elf Realms", "Prince", ["Dragon Helm", "Armour of Caledor"])

    def test_runes_may_be_stacked(self):
        king = build("Dwarfen Mountain Holds", "King",
                     magic_items=["Rune of Might", "Rune of Might", "Rune of Fury"])
        base = build("Dwarfen Mountain Holds", "King")
        self.assertEqual(king.Strength, base.Strength + 2)
        self.assertEqual(king.Attacks, base.Attacks + 1)

    def test_a_character_without_an_allowance_cannot_buy(self):
        with self.assertRaisesRegex(ValueError, "cannot take"):
            build("Dwarfen Mountain Holds", "King", magic_items=["Sword of Might"])

    def test_pick_groups_have_a_limit(self):
        check_purchase("Kingdom of Bretonnia", "Duke", ["Virtue of Heroism"])
        with self.assertRaisesRegex(ValueError, "at most 1"):
            check_purchase("Kingdom of Bretonnia", "Duke",
                           ["Virtue of Heroism", "Virtue of Confidence"])

    def test_chaotic_traits_allow_two(self):
        check_purchase("Warriors of Chaos", "Chaos Lord", ["Brazen Will", "Unnatural Fortitude"])

    def test_a_two_handed_magic_weapon_cannot_be_used_with_a_shield(self):
        two_handed = next(n for n in items_for("Orc & Goblin Tribes")
                          if get_magic_item(n).get("is_weapon")
                          and "Requires Two Hands" in get_weapon_stats(get_magic_item(n)["weapon"])[2]
                          and (get_magic_item(n).get("cost") or 0) <= 100)
        with self.assertRaisesRegex(ValueError, "requires two hands"):
            build("Orc & Goblin Tribes", "Orc Warboss", Shield=True, magic_items=[two_handed])

    def test_an_unknown_item_is_an_error(self):
        with self.assertRaisesRegex(ValueError, "Unknown magic item"):
            build("Orc & Goblin Tribes", "Orc Warboss", magic_items=["Sword of Mighty"])

    def test_a_custom_fighter_may_take_anything(self):
        custom = fighter(magic_items=["Runefang", "Armour of Destiny"])
        self.assertEqual(custom.Weapon, "Runefang")
        self.assertEqual(custom.Armor, "Heavy Armor")

    def test_allowance_lookup(self):
        self.assertEqual(allowance_for("High Elf Realms", "Prince"),
                         {"Magic Items": 100, "Elven Honours": None})
        self.assertEqual(allowance_for("High Elf Realms", "Korhil Lionmane"), {})


class TestItemEffects(unittest.TestCase):
    """Items whose wording is easy to misread."""

    def rules(self, name):
        return fighter(magic_items=[name]).SpecialRules

    def test_bloodskull_pendant_gives_no_killing_blow_to_normal_attacks(self):
        # "Instead of attacking normally ... may choose to inflict a single
        # Strength 8 hit ... These hits have the Killing Blow special rule."
        # Only that optional hit has Killing Blow; it is not simulated.
        entry = get_magic_item("Bloodskull Pendant")
        self.assertEqual(entry["status"], "not modelled")
        self.assertNotIn("Killing Blow", self.rules("Bloodskull Pendant"))

    def test_hits_that_only_retaliate_grant_nothing(self):
        self.assertEqual(self.rules("Crystal of Kunlan"), ["Ward5"])  # not Flaming Attacks
        self.assertNotIn("Strike First", self.rules("Enchanting Aura"))
        self.assertNotIn("Strike First", self.rules("Soporific Musk"))

    def test_the_chariot_of_the_gods_only_affects_impact_hits(self):
        self.assertEqual(self.rules("The Chariot of the Gods"), [])

    def test_a_ward_against_magic_is_not_magical_attacks(self):
        self.assertEqual(self.rules("Talisman of the Soaring Eagle"), ["Ward5 (magical)"])

    def test_two_wards_on_one_item(self):
        rules = self.rules("The White Cloak")
        self.assertEqual(parse_ward(rules), 5)
        self.assertEqual(parse_ward(rules, is_flaming=True), 3)

    def test_negative_modifiers_are_applied(self):
        base = fighter()
        cursed = fighter(Armor="", magic_items=["The Accursed Armour"])
        self.assertEqual(cursed.Toughness, base.Toughness + 1)
        self.assertEqual(cursed.WeaponSkill, base.WeaponSkill - 1)
        self.assertEqual(cursed.Initiative, base.Initiative - 1)
        self.assertEqual(cursed.Armor, "Full Plate Armor")

    def test_modifiers_never_leave_one_to_ten(self):
        weak = fighter(WeaponSkill=1, Initiative=1, magic_items=["The Accursed Armour"])
        self.assertEqual((weak.WeaponSkill, weak.Initiative), (1, 1))

    def test_a_magic_weapons_bonus_needs_the_weapon_in_hand(self):
        wielder = fighter(magic_items=["Chaos Runesword"])
        self.assertEqual((wielder.WeaponSkill, wielder.Initiative), (5, 5))

    def test_armour_improvement_capped_at_two_up_still_applies(self):
        self.assertIn("Improve Armour (1)", self.rules("Dragon Helm"))

    def test_challenge_only_effects_apply_in_a_duel(self):
        # A duel is fought as a challenge.
        self.assertIn("Reroll Failed Hits", self.rules("Virtue of Confidence"))
        self.assertIn("Wound Stealing", self.rules("Gut Maw"))

    def test_runefang_always_wounds_on_a_two(self):
        self.assertIn("Wounds On (2+)", get_weapon_stats("Runefang")[2])

    def test_sword_of_kings_kills_on_a_five(self):
        self.assertIn("Killing Blow 5+", get_weapon_stats("Sword of Kings")[2])

    def test_items_for_war_machines_do_nothing_for_a_character(self):
        for name in ("Rune of Burning", "Rune of Skewering"):
            with self.subTest(item=name):
                self.assertEqual(get_magic_item(name)["status"], "no duel effect")


if __name__ == "__main__":
    unittest.main()
