"""Generate unit_extras.py: base sizes, and wizard levels and lores, from the unit pages.

    python3 tools/transcribe_unit_extras.py        # report
    python3 tools/transcribe_unit_extras.py -w     # write unit_extras.py

    BASE_SIZES = {faction: {profile: (width_mm, depth_mm)}}
    MOUNT_BASES = {mount: (width_mm, depth_mm)}
    WIZARDS = {faction: {profile: {"level": n, "lores": [...]}}}
    CREW = {faction: {profile: n}}     # "Orc Crew (x2)": the profile row stands for n models

Base sizes drive how many models of two units touch; wizard levels and lores
say which spells a character may cast. No rules text is copied.
"""

from __future__ import annotations

import importlib
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path[:0] = [HERE, ROOT]

import tow_site as site  # noqa: E402
import transcribe_faction as tf  # noqa: E402
import verify_rosters as vr  # noqa: E402

OUT = os.path.join(ROOT, "unit_extras.py")
_SIZE = re.compile(r"(\d+)\s*x\s*(\d+)\s*mm", re.I)


def base_size(fields):
    match = _SIZE.search(fields.get("baseSize") or "")
    return (int(match.group(1)), int(match.group(2))) if match else None


def wizard_level(value):
    """1-4 from "1", "Level 2", 3 ...; None if not a Wizard."""
    match = re.search(r"\d", str(value or ""))
    return int(match.group()) if match else None


def build():
    bases, wizards, crew, missing = {}, {}, {}, []
    for cfg in tf.FACTIONS.values():
        if not cfg.get("module"):
            continue
        module = importlib.import_module(f"factions.{cfg['module']}")
        profiles = {**module.CHARACTERS, **getattr(module, "UNITS", {})}
        folded = {vr._fold(k): k for k in profiles}
        for _section, slug, name in site.army_units(cfg["army"]):
            mine = folded.get(vr._fold(vr.SITE_NAMES.get(name, name)))
            if not mine:
                continue
            fields = site.entry(f"unit/{slug}")["fields"]
            size = base_size(fields)
            if size:
                bases.setdefault(cfg["faction"], {})[mine] = size
            else:
                missing.append(f"{cfg['faction']}/{mine}")
            # The row that carries Leadership is the one the roster's statline
            # comes from; "(x2)" on it means two crew models share it.
            for row in site.unit(slug)["profiles"]:
                count = re.search(r"\(x(\d+)\)", row.get("Name") or "")
                if count and str(row.get("Ld", "-")).strip() not in ("-", ""):
                    crew.setdefault(cfg["faction"], {})[mine] = int(count.group(1))
            level = wizard_level(fields.get("wizardLevel"))
            if level:
                lores = [l["fields"]["name"] for l in fields.get("magicLore") or [] if "fields" in l]
                wizards.setdefault(cfg["faction"], {})[mine] = {"level": level, "lores": lores}
    from mounts import Mounts

    mount_bases = {}
    for mount, data in Mounts.items():
        slug = data.get("url")
        if not slug:
            continue
        try:
            size = base_size(site.entry(f"unit/{slug}")["fields"])
        except site.PageNotFound:
            size = None
        if size:
            mount_bases[mount] = size
    return bases, mount_bases, wizards, crew, missing


def render(bases, mount_bases, wizards, crew):
    lines = ['"""Base sizes and Wizard levels, from tow.whfb.app.', "",
             "GENERATED by tools/transcribe_unit_extras.py - do not edit by hand.", '"""', "",
             "BASE_SIZES = {"]
    for faction in sorted(bases):
        lines.append(f"    {faction!r}: {{")
        lines += [f"        {p!r}: {bases[faction][p]!r}," for p in sorted(bases[faction])]
        lines.append("    },")
    lines += ["}", "", "MOUNT_BASES = {"]
    lines += [f"    {m!r}: {mount_bases[m]!r}," for m in sorted(mount_bases)]
    lines += ["}", "", "WIZARDS = {"]
    for faction in sorted(wizards):
        lines.append(f"    {faction!r}: {{")
        lines += [f"        {p!r}: {wizards[faction][p]!r}," for p in sorted(wizards[faction])]
        lines.append("    },")
    lines += ["}", "", "CREW = {"]
    for faction in sorted(crew):
        lines.append(f"    {faction!r}: {{")
        lines += [f"        {p!r}: {crew[faction][p]!r}," for p in sorted(crew[faction])]
        lines.append("    },")
    lines.append("}")
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    bases, mount_bases, wizards, crew, missing = build()
    print(sum(map(len, bases.values())), "profiles with base sizes,", len(mount_bases), "mounts,",
          sum(map(len, wizards.values())), "wizards,", sum(map(len, crew.values())), "crewed profiles;",
          len(missing), "without a base size")
    if "-v" in sys.argv:
        print("\n".join("   " + m for m in missing))
    if "-w" in sys.argv:
        with open(OUT, "w", encoding="utf-8") as fh:
            fh.write(render(bases, mount_bases, wizards, crew))
        print("wrote", OUT)
