"""Generate item_allowances.py: what each character may buy, from its unit page.

    python3 tools/transcribe_allowances.py -w

A character's options say how many points it may spend on each kind of item
("may purchase magic items up to a total of 100 points", "Daemonic Gifts up to
a total of 50 points") and which abilities it may pick without a points cap
("may have an Elven Honour", "may take a Knightly Virtue"). The result is
{faction: {profile: {budget: points or None}}}, where None means "may pick
from this group" with no points limit of its own.

Named characters are not listed: their wargear is fixed.
"""

from __future__ import annotations

import importlib
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path[:0] = [HERE, ROOT]

import tow_site as site  # noqa: E402
import transcribe_faction as tf  # noqa: E402
import verify_rosters as vr  # noqa: E402

OUT = os.path.join(ROOT, "item_allowances.py")

# Allowance wording -> budget name.
BUDGETS = [
    (r"weapon, armour and talismanic runes|weapon runes|armour runes|talismanic runes"
     r"|standard runes|engineering runes|\bruness?\b", "Runes"),
    (r"daemonic gifts", "Daemonic Gifts"),
    (r"gifts of chaos", "Gifts of Chaos"),
    (r"chaos mutations", "Chaos Mutations"),
    (r"forest spites", "Forest Spites"),
    (r"vampiric powers", "Vampiric Powers"),
    (r"magic items|magic standard", "Magic Items"),
]

# Abilities picked without a points allowance, by the wording that offers them.
FREE_PICKS = [
    (r"elven honour", "Elven Honours"),
    (r"knightly virtue", "Knightly Virtues"),
    (r"noble kindred|\bkindred\b", "Noble Kindreds"),
    (r"chaotic trait", "Chaotic Traits"),
    (r"big name", "Big Names"),
    (r"runic tattoo", "Runic Tattoos"),
    (r"discipline", "Disciplines of the Old Ones"),
    (r"infamous origin", "Infamous Origins"),
    (r"knightly order", "Knightly Orders"),
]

# Ability groups an army offers to its characters in general rather than on
# each character's page. The items' own text says which characters qualify.
ARMY_PICKS = {
    "Wood Elf Realms": ["Noble Kindreds", "Alter Kindreds"],
    "Empire of Man": ["Knightly Orders"],
    "Realms of Men": ["Infamous Origins"],
}

_TOTAL = re.compile(r"([^\n.]*?) up to a total of (\d+) points?", re.I)


def allowances(options):
    found = {}
    for what, points in _TOTAL.findall(options):
        for pattern, budget in BUDGETS:
            if re.search(pattern, what, re.I):
                found[budget] = found.get(budget, 0) + int(points)
                break
    for pattern, group in FREE_PICKS:
        if re.search(pattern, options, re.I):
            found.setdefault(group, None)
    return found


def build():
    result = {}
    for key, cfg in tf.FACTIONS.items():
        if not cfg.get("module"):
            continue
        module = importlib.import_module(f"factions.{cfg['module']}")
        folded = {vr._fold(k): k for k in module.CHARACTERS}
        for section, slug, name in site.army_units(cfg["army"]):
            if section.strip().lower() != "character":
                continue  # named characters have fixed wargear
            mine = folded.get(vr._fold(vr.SITE_NAMES.get(name, name)))
            if not mine:
                continue
            found = allowances(site.unit(slug)["options"])
            for group in ARMY_PICKS.get(cfg["faction"], []):
                found.setdefault(group, None)
            if found:
                result.setdefault(cfg["faction"], {})[mine] = found
    return result


def render(result):
    lines = ['"""What each character may buy: {faction: {profile: {budget: points or None}}}.',
             "",
             "GENERATED by tools/transcribe_allowances.py - do not edit by hand.",
             "None means the character may pick from that group with no points cap.",
             '"""', "", "ALLOWANCES = {"]
    for faction in sorted(result):
        lines.append(f"    {faction!r}: {{")
        for profile in sorted(result[faction]):
            lines.append(f"        {profile!r}: {result[faction][profile]!r},")
        lines.append("    },")
    lines.append("}")
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    data = build()
    total = sum(len(v) for v in data.values())
    print(total, "characters with allowances")
    if "-w" in sys.argv:
        with open(OUT, "w", encoding="utf-8") as fh:
            fh.write(render(data))
        print("wrote", OUT)
    else:
        for faction, profiles in data.items():
            for profile, found in profiles.items():
                print(f"{faction:25} {profile:35} {found}")
