"""Generate spells_data.py: every spell's lore, type, casting value, range and duration.

    python3 tools/transcribe_spells.py        # report
    python3 tools/transcribe_spells.py -w     # write spells_data.py

    SPELLS = {name: {"lore": ..., "type": ..., "cv": n, "range": ..., "duration": ...}}

`duration` is read from the spell's wording:
    "turn"     until the end of this turn (the caster's turn only)
    "round"    until the caster's next Start of Turn sub-phase
    "phase"    until the end of the Combat phase
    "rip"      Remains in Play
    "instant"  no lasting effect

What a spell does in a fight is written by hand in spells.py; no rules text is
copied here.
"""

from __future__ import annotations

import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path[:0] = [HERE, ROOT]

import tow_site as site  # noqa: E402

OUT = os.path.join(ROOT, "spells_data.py")


def _text(node):
    if isinstance(node, list):
        return "".join(_text(c) for c in node)
    if not isinstance(node, dict):
        return ""
    if node.get("nodeType") == "text":
        return node.get("value", "")
    sep = "\n" if node.get("nodeType") in ("paragraph", "list-item", "table-row") else " "
    return "".join(_text(c) for c in node.get("content", [])) + sep


def _lore_spells(node):
    """(lore name, [spell entries]) for every lore table embedded in a page."""
    if isinstance(node, dict):
        if isinstance(node.get("spell"), list) and "target" in node:
            yield node["target"].get("fields", {}).get("name"), node["spell"]
        for value in node.values():
            yield from _lore_spells(value)
    elif isinstance(node, list):
        for value in node:
            yield from _lore_spells(value)


def duration(text):
    low = " ".join(text.lower().split())
    if "remains in play" in low:
        return "rip"
    if re.search(r"until (the end of )?your next start of turn", low):
        return "round"
    if "until the end of this turn" in low or "lasts until the end of this turn" in low:
        return "turn"
    if "until the end of the combat phase" in low:
        return "phase"
    return "instant"


def spell_type(text):
    match = re.search(r"Type\s+(Enchantment|Hex|Conveyance|Magic Missile|Magical Vortex|Assailment)", text)
    return match.group(1) if match else None


def build():
    lores = [r["fields"]["slug"] for r in site.page("sitemap/rules")["rules"]
             if (r["fields"].get("ruleType") or [{}])[0].get("fields", {}).get("slug") == "the-lores-of-magic"]
    spells = {}
    for lore in lores:
        for lore_name, entries in _lore_spells(site.page(f"the-lores-of-magic/{lore}")):
            for entry in entries:
                f = entry.get("fields", {})
                if not f.get("name"):
                    continue
                text = _text(f.get("body"))
                spells[f["name"]] = {
                    "lore": lore_name,
                    "type": spell_type(text),
                    "cv": f.get("castingValue"),
                    "range": f.get("range"),
                    "duration": duration(text),
                    "slug": f.get("slug"),
                }
    return spells


def render(spells):
    lines = ['"""Spell index, from tow.whfb.app.', "",
             "GENERATED by tools/transcribe_spells.py - do not edit by hand.", '"""', "",
             "SPELLS = {"]
    lines += [f"    {name!r}: {spells[name]!r}," for name in sorted(spells)]
    lines.append("}")
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    spells = build()
    from collections import Counter

    print(len(spells), "spells;", dict(Counter(s["type"] for s in spells.values())))
    print(dict(Counter(s["duration"] for s in spells.values())))
    if "-w" in sys.argv:
        with open(OUT, "w", encoding="utf-8") as fh:
            fh.write(render(spells))
        print("wrote", OUT)
